# German Pokedex paragraphs
PARAGRAPHS = {
    "BulbasaurPokedexEntry": "Solange es jung ist, nutzt es Nährstoffe aus den Samen auf seinem Rücken zum Wachsen.",
    "IvysaurPokedexEntry": "Die Knospe auf seinem Rücken wächst und nimmt Nährstoffe auf. Beim Blühen verströmt sie Duft.",
    "VenusaurPokedexEntry": "Wärmt es sich und nimmt Sonnenlicht auf, verströmen seine Blüten einen angenehmen Duft.",
    "CharmanderPokedexEntry": "Ist es gesund, brennt die Flamme an seiner Schwanzspitze kräftig, selbst wenn es etwas nass wird.",
    "CharmeleonPokedexEntry": "Wird es im Kampf wütend, stößt es heftige Flammen aus und verbrennt damit seine Umgebung.",
    "CharizardPokedexEntry": "Mit seinen Flügeln fliegt es hoch. Die Feuertemperatur steigt mit seiner Kampferfahrung.",
    "SquirtlePokedexEntry": "Fühlt es sich bedroht, zieht es die Beine in seinen Panzer und spritzt Wasser aus dem Mund.",
    "WartortlePokedexEntry": "Sein langer Schweif ist ein Symbol für Langlebigkeit und macht es bei älteren Menschen beliebt.",
    "BlastoisePokedexEntry": "Es pflanzt die Füße fest auf den Boden, bevor es Wasser aus den Düsen auf seinem Rücken abschießt.",
    "CaterpiePokedexEntry": "Es kriecht in Blätterwerk, wo es sich unter gleichfarbigen Blättern tarnt.",
    "MetapodPokedexEntry": "Dies ist seine Vorstufe. Es kann nur erstarren und bleibt regungslos, um Angriffen auszuweichen.",
    "ButterfreePokedexEntry": "Es flattert von Blume zu Blume und sammelt Nektar. Es kann sogar weit entfernte blühende Blumen erkennen.",
    "WeedlePokedexEntry": "Der Stachel auf seinem Kopf sondert Gift ab. Es nutzt ihn zur Verteidigung.",
    "KakunaPokedexEntry": "Es ist kaum bewegungsfähig und lehnt sich an starke Bäume, während es auf seine Entwicklung wartet.",
    "BeedrillPokedexEntry": "Es besiegt Beute mit scharfen, giftigen Stacheln und bringt sie in sein Nest als Nahrung.",
    "PidgeyPokedexEntry": "Es schlägt schnell mit den Flügeln im Gras und wirbelt Staub auf, um Insektenbeute hervorzulocken.",
    "PidgeottoPokedexEntry": "Es fliegt langsam im Kreis und hält dabei Ausschau nach Beute.",
    "PidgeotPokedexEntry": "Dieses #mon fliegt mit Mach-2 auf Beutejagd. Seine Krallen sind furchterregende Waffen.",
    "RattataPlainPokedexEntry": "Die enorme Vitalität dieses #mon erlaubt es ihm, überall zu leben. Es vermehrt sich auch sehr schnell.",
    "RaticatePlainPokedexEntry": "Schwimmhäute an seinen Hinterbeinen ermöglichen Flussüberquerungen. Es sucht weit nach Nahrung.",
    "SpearowPokedexEntry": "Zum Schutz seines Reviers fliegt es unaufhörlich umher und gibt hohe Schreie von sich.",
    "FearowPokedexEntry": "Es greift mit seinem langen Schnabel an. Seine Reichweite ist groß, Vorsicht!",
    "EkansPokedexEntry": "Es züngelt mit der Zungenspitze, um den Geruch von Beute zu erschnüffern, und schluckt sie dann im Ganzen.",
    "ArbokPokedexEntry": "Um Gegner einzuschüchtern, breitet es die Brust weit und stößt unheimliche Laute aus seinem Maul.",
    "PikachuPokedexEntry": "Wenn es wütend ist, entlädt es sofort die in den Backentaschen gespeicherte Energie.",
    "RaichuPlainPokedexEntry": "Sind seine elektrischen Backentaschen leer, hebt es den Schweif, um Elektrizität aus der Luft zu sammeln.",
    "SandshrewPlainPokedexEntry": "Es bevorzugt trockene, sandige Orte, da es den Sand zum Schutz nutzt, wenn es bedroht wird.",
    "SandslashPlainPokedexEntry": "Es kann gut klettern, rollt sich zu einem stacheligen Ball und greift Gegner von oben an.",
    "NidoranFPokedexEntry": "Klein und sehr fügsam, schützt es sich mit seinem kleinen, giftigen Horn, wenn es angegriffen wird.",
    "NidorinaPokedexEntry": "Es hat ein sanftes Wesen. Wird es bedroht, richtet es die Stacheln über seinem ganzen Körper auf.",
    "NidoqueenPokedexEntry": "Die harten Schuppen auf seinem Körper bieten ausgezeichneten Schutz vor jedem Angriff.",
    "NidoranMPokedexEntry": "Es bewegt ständig seine großen Ohren in viele Richtungen, um Gefahr sofort zu erkennen.",
    "NidorinoPokedexEntry": "Es ist leicht reizbar und stößt mit seinem Horn an, sobald es einen Angreifer bemerkt.",
    "NidokingPokedexEntry": "Es greift mit Armen, Beinen und Schweif kraftvoll an. Nahkampf ist seine Spezialität.",
    "ClefairyPokedexEntry": "Aufgrund des gespeicherten Mondlichts in seinen Flügeln auf dem Rücken kann es in der Luft.",
    "ClefablePokedexEntry": "Ein feenhaftes und scheues #mon, das sofort die Flucht ergreift, wenn es Menschen wittert.",
    "VulpixPlainPokedexEntry": "In seiner Jugend hat es sechs hinreißende Schweife.",
    "NinetalesPlainPokedexEntry": "Dieses #mon ist intelligent, aber rachsüchtig.",
    "JigglypuffPokedexEntry": "Wenn es Gesang einsetzt, steigt seine Ausdauer und seine Zuhörer werden in versetzt Tiefschlaf.",
    "WigglytuffPokedexEntry": "Der Körper dieses #mon ist sehr elastisch. Bei Gefahr bläht es sich zu enormer Körpergröße auf.",
    "ZubatPokedexEntry": "Es hat keine Augen.",
    "GolbatPokedexEntry": "Hat es einmal angefangen Blut zu saugen, hört es erst wieder auf, wenn es satt ist.",
    "OddishPokedexEntry": "Sein wissenschaftlicher Name lautet: „Oddium Wanderus“.",
    "GloomPokedexEntry": "Der Honig, den es abgibt, riecht so entsetzlich, dass sich sogar Nasen in 2 km Entfernung.",
    "VileplumePokedexEntry": "Es besitzt die größten Blätter der Welt. Bei jedem Schritt streut es Boden Giftpollen zu.",
    "ParasPokedexEntry": "Dieses #mon gräbt sich in den Boden und frisst Wurzeln.",
    "ParasectPokedexEntry": "Je größer der Pilz auf seinem Rücken wird, desto stärker werden auch die Sporen, die es.",
    "VenonatPokedexEntry": "Dieses #mon lebt im Schatten großer Bäume. Es frisst Insekten und wird von Licht angezogen.",
    "VenomothPokedexEntry": "Seine Flügel sind mit staubähnlichen Schuppen überzogen.",
    "DiglettPlainPokedexEntry": "Seine Haut ist sehr dünn.",
    "DugtrioPlainPokedexEntry": "Es ist so stark, dass es sich mit Schaufler sogar durch steinharten Boden bis in 100 km Tiefe.",
    "MeowthPlainPokedexEntry": "Dieses #mon bewundert runde Objekte. Es sucht nachts auf den Straßen nach verlorenen Münzen.",
    "PersianPlainPokedexEntry": "Aufgrund seiner geschmeidigen Muskeln kann es sich lautlos bewegen.",
    "PsyduckPokedexEntry": "Es besitzt mystische Kräfte, die es unbewusst einsetzt. Daher ist sein Blick immer verwirrt.",
    "GolduckPokedexEntry": "Seine Vorderbeine besitzen Schwimmhäute, um es perfekt ans Wasser anzupassen.",
    "MankeyPokedexEntry": "Es lebt mit anderen in Baumkronen.",
    "PrimeapePokedexEntry": "Es ist immer außerordentlich wütend.",
    "GrowlithePokedexEntry": "Es ist von Natur aus tapfer und vertrauenswürdig. Es scheut nicht vor starken Gegnern zurück.",
    "ArcaninePokedexEntry": "Sein bezauberndes Bellen klingt majestätisch.",
    "PoliwagPokedexEntry": "Dieses #mon kann sehr schlecht laufen. Sein Bauchmuster ist unterschiedlich, je nach Region.",
    "PoliwhirlPokedexEntry": "Seine beiden Beine sind gut entwickelt.",
    "PoliwrathPokedexEntry": "Dieses #mon ist ein meisterhafter Schwimmer. Seine Techniken schlagen selbst Olympiasieger.",
    "AbraPokedexEntry": "Es sieht die Attacken der Gegner voraus und setzt Teleport ein, um sich in Sicherheit zu.",
    "KadabraPokedexEntry": "Setzt es seine Kräfte ein, sendet es Alphawellen aus, die einen Defekt bei en Maschinen erzeug-.",
    "AlakazamPokedexEntry": "Das Gehirn dieses #mon ist leistungsfähiger als ein Computer.",
    "MachopPokedexEntry": "Sein ganzer Körper besteht aus Muskeln.",
    "MachokePokedexEntry": "Es kann einen LKW mit einer Hand hochheben.",
    "MachampPokedexEntry": "Es setzt seine vier Arme ein, um die Glieder seiner Gegner festzuhalten.",
    "BellsproutPokedexEntry": "Seine Knospe ähnelt einem Menschengesicht.",
    "WeepinbellPokedexEntry": "Dieses #mon lähmt den Gegner mit Giftpuder, bevor es ihn mit Säure erledigt.",
    "VictreebelPokedexEntry": "Selbst die härtesten Objekte werden zersetzt, wenn der Körper sie erst aufgenommen hat.",
    "TentacoolPokedexEntry": "Dieses #mon findet man in flachen Gewässern. Unachtsame Gegner empfängt es mit brennendem Gift.",
    "TentacruelPokedexEntry": "Es verfügt über 80 Tentakel, die es frei bewegen kann.",
    "GeodudePlainPokedexEntry": "Man kann es nicht von Felsbrocken unterscheiden. Es rempelt andere an, um sich zu beweisen.",
    "GravelerPlainPokedexEntry": "Dieses #mon bewegt sich nur rollend fort. Kein Hindernis kann es vom Kurs abbringen.",
    "GolemPlainPokedexEntry": "Selbst Sprengstoff kann seinem harten Körper nichts anhaben. Häutet sich nur einmal jährlich.",
    "PonytaPlainPokedexEntry": "Seine Beine werden kräftig, da es seinen Eltern hinterherläuft. Es rennt den ganzen Tag umher.",
    "RapidashPlainPokedexEntry": "Seine Mähne lodert auf, wenn es mit 240 km/h pfeilschnell galoppiert.",
    "SlowpokePlainPokedexEntry": "Es faulenzt am Wasser.",
    "SlowbroPlainPokedexEntry": "Als Flegmon im Wasser jagen ging, wurde es von einem Muschas gebissen.",
    "MagnemitePokedexEntry": "Es bewegt sich schwebend.",
    "MagnetonPokedexEntry": "Dieses #mon erzeugt seltsame Radiowellen und kann die anheben Lufttemperatur geringfügig.",
    "FarfetchDPlainPokedexEntry": "Es läuft stets mit einer Lauchstange umher. Damit baut es sein Nest.",
    "DoduoPokedexEntry": "Die Gehirne der beiden Köpfe kommunizieren ihre Gefühle über Telepathie.",
    "DodrioPokedexEntry": "Ein seltsames Exemplar, das nur selten gefunden wird.",
    "SeelPokedexEntry": "Unter seinem hellblauen Pelz liegt eine dicke und feste Haut.",
    "DewgongPokedexEntry": "Es verspürt kaum Widerstand im Wasser.",
    "GrimerPlainPokedexEntry": "Dieses #mon lebt vorwiegend in schmutzigen Gebieten und ernährt sich von Industrieabfällen.",
    "MukPlainPokedexEntry": "Sein Körper sondert eine giftige Substanz ab, die bei htet Kontakt Pflanzen und Bäume vernic-.",
    "ShellderPokedexEntry": "Da es seine verwundbarste Stelle beim Klammern lichen preisgibt, tut es dies nur in wirk-.",
    "CloysterPokedexEntry": "Sein Panzer ist extrem hart. Es kann nicht zerschmettert werden, auch nicht durch eine Bombe.",
    "GastlyPokedexEntry": "Eingehüllt in seinen fallen gasförmigen, Gift enthaltenden Körper würde jeder in Ohnmacht.",
    "HaunterPokedexEntry": "Es beleckt seine Opfer mit seiner Zunge und stiehlt ihnen so Lebenskraft.",
    "GengarPokedexEntry": "Es versteckt sich im Schatten der Menschen und absorbiert deren Wärme, sodass die Menschen.",
    "OnixPokedexEntry": "Es lebt gewöhnlich unter der Erde.",
    "DrowzeePokedexEntry": "Hast du gut geträumt und kannst dich nicht erinnern, hat ein Traumato deinen Traum gefressen.",
    "HypnoPokedexEntry": "Ein Blick auf das Pendel versetzt einen in drei Sekunden in nicht Schlaf, selbst wenn man gar.",
    "KrabbyPokedexEntry": "Es kommt vor allem nahe des Meeres vor.",
    "KinglerPokedexEntry": "Seine Scheren werden sehr groß. Hebt es sie zu schnell, verliert es die Balance und strauchelt.",
    "VoltorbPokedexEntry": "Dieses #mon wird oftmals mit einem Pokéball verwechselt. Es lebt vorwiegend in Kraftwerken.",
    "ElectrodePokedexEntry": "Es speichert eine riesige Menge Elektrizität in seinem Körper.",
    "ExeggcutePokedexEntry": "Auch wenn sein Erscheinungsbild eher Eiern ähnelt, wurde entdeckt, dass es mehr mit.",
    "ExeggutorPlainPokedexEntry": "Man nennt es den „Laufenden Dschungel“.",
    "CubonePokedexEntry": "Es trägt immer den Schädel seiner verstorbenen Mutter.",
    "MarowakPlainPokedexEntry": "Der Knochen, den dieses #mon hält, ist seine Primärwaffe. Es wirft ihn wie einen Bumerang.",
    "HitmonleePokedexEntry": "Wenn es anfängt pausenlos zu treten, kann es seine Beine ausfahren, um zu fliehende Feinde.",
    "HitmonchanPokedexEntry": "Der Geist eines Profi-Boxers hat dieses #mon inspiriert.",
    "LickitungPokedexEntry": "Seine Zunge ist doppelt so lang wie sein Körper.",
    "KoffingPokedexEntry": "Gase, die leichter als Luft sind, lassen es schweben. Diese Gase stinken und sind explosiv.",
    "WeezingPlainPokedexEntry": "Sehr selten führt eine plötzliche Mutation eines Zwillings-Smogon zu einer Verbindung zu.",
    "RhyhornPokedexEntry": "Aufgrund seiner kurzen Beine kann es sich nicht umdrehen.",
    "RhydonPokedexEntry": "Nach seiner Entwicklung geht es aufrecht auf seinen Hinterfüßen.",
    "ChanseyPokedexEntry": "Es legt mehrere Eier am Tag. Sie sind sehr nahrhaft und außerordentlich schmackhaft.",
    "TangelaPokedexEntry": "Es berührt alles, was sich bewegt, mit seinen Ranken. Diese Berührungen kitzeln sehr.",
    "KangaskhanPokedexEntry": "Fühlt es sich sicher, dann verlässt das Junge den Beutel. Die Mutter behält es ständig im Auge.",
    "HorseaPokedexEntry": "Im Schatten von Korallen legt es sein Nest an. Bei Gefahr versprüht es Tinte und flieht.",
    "SeadraPokedexEntry": "Dieses #mon kann rückwärts schwimmen, indem es Flügel und Schwanz als Flossen einsetzt.",
    "GoldeenPokedexEntry": "Seine Brust-, Rücken- und Schweifflossen sehen anmutig aus.",
    "SeakingPokedexEntry": "Es baut Nester, indem es Steine im Fluss mit seinem Horn aushöhlt.",
    "StaryuPokedexEntry": "Es taucht in großer Anzahl an Ufern auf. Nachts leuchtet der Kern in seiner Mitte rot auf.",
    "StarmiePokedexEntry": "In der Körpermitte befindet sich ein roter Kern, der mysteriöse Radiowellen in die Nacht.",
    "MrMimePlainPokedexEntry": "Es ist geschickt darin, Menschen zu beeinflussen.",
    "ScytherPokedexEntry": "Es bewegt sich mit seinen Sensen so schnell durch das Gras, dass es kein Mensch sehen kann.",
    "JynxPokedexEntry": "Es spricht und benutzt dabei eine Sprache, die der des Menschen sehr ähnelt.",
    "ElectabuzzPokedexEntry": "Es konsumiert am liebsten Elektrizität. Gelegentlich sieht man es in der Nähe von Kraftwerken.",
    "MagmarPokedexEntry": "Es wurde bei einem Vulkanausbruch geboren. Sein Körper ist von hellen Flammen umgeben.",
    "PinsirPokedexEntry": "Beim Angriff verdreht es sein Geweih. In Kälteperioden versteckt es sich tief im Wald.",
    "TaurosPlainPokedexEntry": "Wenn es Tackle einsetzt, geißelt es mit seinen drei Schwänzen wiederholt seinen Körper.",
    "MagikarpPokedexEntry": "Die urzeitlichen Vorfahren dieses #mon waren sehr viel stärker als ihre heutigen Nachkommen.",
    "GyaradosPlainPokedexEntry": "Ein gigantisches, sehr kraftvolles #mon. Es ist fähig, ganze Städte zu zerstören.",
    "LaprasPokedexEntry": "Aufgrund seiner hohen Intelligenz kann es die menschliche Sprache verstehen.",
    "DittoPokedexEntry": "Es kann seine eigene Zellstruktur frei zusammensetzen und sich in jede andere Lebensform.",
    "EeveePokedexEntry": "Aufgrund einer genetischen Anomalie kann seine Entwicklung viele verschiedene Formen annehmen.",
    "VaporeonPokedexEntry": "Es hat sich so entwickelt, dass es im Wasser leben kann. Im Wasser selbst wird es unsichtbar.",
    "JolteonPokedexEntry": "Dieses #mon entzieht der Atmosphäre Ionen, die es in Blitze von 10 000 V Stärke umwandelt.",
    "FlareonPokedexEntry": "In seinem Körper hat es eine Flammentasche.",
    "PorygonPokedexEntry": "Porygon besteht komplett aus Computerdaten. Es kann sich frei in virtuellen Welten bewegen.",
    "OmanytePokedexEntry": "Es wurde aus einem Fossil reanimiert.",
    "OmastarPokedexEntry": "Hat es die Beute erst eingewickelt, lässt es nicht mehr los.",
    "KabutoPokedexEntry": "Dieses #mon wurde aus dem Fossil einer altertümlichen Kreatur geschaffen.",
    "KabutopsPokedexEntry": "Dieses #mon ist ein sehr guter Schwimmer. Es attackiert Gegner mit seinen Sichelarmen.",
    "AerodactylPokedexEntry": "Dieses grausame, antike #mon flog durch die Luft und stieß sehr hohe und laute Schreie aus.",
    "SnorlaxPokedexEntry": "Sein Magen kann jede Art von Nahrung verdauen, selbst wenn sie verschimmelt und verdorben ist.",
    "ArticunoPlainPokedexEntry": "Ein Legendäres Vogel-#mon, das angeblich in Gletschern verirrten weist Wanderern den Weg.",
    "ZapdosPlainPokedexEntry": "Ein Legendäres Vogel-#mon, das in Gewitterwolken leben soll. Es kontrolliert Blitze.",
    "MoltresPlainPokedexEntry": "Eines der Legendären Vogel-#mon. Es wird als Bote des Frühlings angesehen.",
    "DratiniPokedexEntry": "Dieses #mon strotzt vor Lebensenergie. Es häutet sich ständig und wird dadurch größer.",
    "DragonairPokedexEntry": "Ein mysteriöses #mon mit einer sehr freundlichen Ausstrahlung. Es kann das Klima beeinflussen.",
    "DragonitePokedexEntry": "Man sagt, es lebe in den Meeren. Es bringt Schiffbrüchige sicher an Land.",
    "MewtwoPlainPokedexEntry": "Die Gene von Mew wurden neu angeordnet, Herz wodurch dieses #mon entstand. Es hat ein wildes.",
    "MewPokedexEntry": "Seine DNS soll den genetischen Code aller #mon beinhalten.",
    "ChikoritaPokedexEntry": "Mit dem Blatt auf seinem Kopf bestimmt es die Temperatur und Feuchtigkeit.",
    "BayleefPokedexEntry": "Die Knospen an seinem Hals geben ein würziges Aroma ab, das andere aufheitert.",
    "MeganiumPokedexEntry": "Meganie kann mit seinem Atem abgestorbene Gräser und Pflanzen reanimieren.",
    "CyndaquilPokedexEntry": "Erschrickt sich dieses scheue #mon, lodern die Flammen auf seinem Rücken kräftiger.",
    "QuilavaPokedexEntry": "Dreht es dir im Kampf den Rücken zu, wird es dich mit den Flammen seines Rückens angreifen.",
    "TyphlosionPlainPokedexEntry": "Es verfügt über eine verheerende Geheimattacke. Es reibt sein Fell, um Explosionen zu erzeugen.",
    "TotodilePokedexEntry": "Seine starken Kiefer können alles zermalmen.",
    "CroconawPokedexEntry": "Hat es einmal zugebissen, lässt es erst los, wenn es seine Zähne verliert, die schnell.",
    "FeraligatrPokedexEntry": "Wenn es mit seinem kräftigen Kiefer zubeißt, schüttelt es seinen Kopf und reißt seine Opfer in.",
    "SentretPokedexEntry": "Es stellt sich auf den Schweif, um weiter zu blicken.",
    "FurretPokedexEntry": "Sein Nest ist seinem schmalen und dünnen Körper angepasst. Kein anderes #mon kommt hinein.",
    "HoothootPokedexEntry": "Es steht immer auf einem Bein. Es wechselt sein Standbein so schnell, dass man es kaum sieht.",
    "NoctowlPokedexEntry": "Muss es nachdenken, dreht es seinen Kopf um 180 Grad, um so seinen Intellekt zu schärfen.",
    "LedybaPokedexEntry": "Es ist scheu und stets mit Artgenossen zusammen.",
    "LedianPokedexEntry": "Die Größe des gepunkteten ammen Musters hängt direkt mit der Anzahl der Sterne am Firmament zus-.",
    "SpinarakPokedexEntry": "Es sitzt tagelang regungslos in seinem Netz und lauert unvorsichtiger ihm Beute auf, die zu.",
    "AriadosPokedexEntry": "Es befestigt Seide an der Beute und lässt sie frei.",
    "CrobatPokedexEntry": "Dank seiner vier Flügel kann es sich seiner Beute noch schneller und leiser nähern, ohne dabei.",
    "ChinchouPokedexEntry": "Es verschießt negative und positive Feinde Elektronen seine zwischen seinen Antennen, um zu.",
    "LanturnPokedexEntry": "Es blendet seine Beute mit einem starken Blitz und verschlingt die gelähmte Beute mit einem.",
    "PichuPokedexEntry": "Es kann noch nicht mit Elektrizität umgehen.",
    "CleffaPokedexEntry": "In Nächten mit vielen unden Sternschnuppen sieht man diese #mon. Am Morgen sind sie verschw-.",
    "IgglybuffPokedexEntry": "Sein Körper ist sehr weich.",
    "TogepiPokedexEntry": "Ein Sprichwort besagt, dass Glück dem widerfährt, dem es gelingt, ein schlafendes Togepi zu.",
    "TogeticPokedexEntry": "Man sagt, es zeigt sich nur gutherzigen und einfühlsamen Menschen.",
    "NatuPokedexEntry": "Gewöhnlich sucht es am Boden nach Futter, aber manchmal springt es auch auf Äste, um dort zu.",
    "XatuPokedexEntry": "Man sagt, es sei so still und in sich gekehrt, weil es die Zukunft und die Vergangenheit.",
    "MareepPokedexEntry": "Es speichert viel Luft in seinem weichen Pelz.",
    "FlaaffyPokedexEntry": "Hat es sich mit Elektrizität aufgeladen, leuchtet sein Schweif und es die feuert Haare ab,.",
    "AmpharosPokedexEntry": "Seine Schweifspitze ist so hell, dass viele Verschollene es als kt nutzen Orientierungspun-.",
    "BellossomPokedexEntry": "Sobald die Regenzeit vorbei ist, wird es von der warmen Sonne nach draußen gezogen, wo es.",
    "MarillPokedexEntry": "Seine untergeht Schweifspitze ist mit Öl gefüllt, das leichter als Wasser ist, sodass es nicht.",
    "AzumarillPokedexEntry": "Das blasenähnliche Muster auf seinem Bauch hilft ihm, sich perfekt zu tarnen, wenn es im.",
    "SudowoodoPokedexEntry": "Es tarnt sich als Baum, um nicht angegriffen zu werden.",
    "PolitoedPokedexEntry": "Hören Quapsel und Quaputzi seinen Ruf, antworten sie, indem sie sich von nah und fern.",
    "HoppipPokedexEntry": "Es reitet auf dem Wind. Man sagt, wenn sich Hoppspross versammeln, kommt der Frühling bald.",
    "SkiploomPokedexEntry": "Es öffnet seine Blüte, um Sonnenlicht aufzunehmen.",
    "JumpluffPokedexEntry": "Auch im stärksten Wind kann es kontrollieren, wo seine Saat auf dem Erdball niedergehen soll.",
    "AipomPokedexEntry": "Sein Schweif ist so kräftig, dass es sich stundenlang damit an einem Ast in der Luft halten.",
    "SunkernPokedexEntry": "Es ernährt sich ausschließlich von den Tautropfen, die von den Blättern über ihm hinabfallen.",
    "SunfloraPokedexEntry": "Warmes Sonnenlicht gibt ihm Energie. Daher wandert es stets dem Sonnenlicht hinterher.",
    "YanmaPokedexEntry": "Schlägt es schnell mit den Flügeln, erzeugt es Schockwellen, durch die sogar Fenster.",
    "WooperPlainPokedexEntry": "Wenn es am Abend kühler wird, kommen sie an Land, um nach Nahrung zu suchen.",
    "QuagsirePokedexEntry": "Dieses genügsame #mon ist sehr umgänglich. Beim Schwimmen stößt es immer wieder gegen Schiffe.",
    "EspeonPokedexEntry": "Die Haare seines Fells sind so feinfühlig, dass es am Wind ablesen kann, was seine Gegner.",
    "UmbreonPokedexEntry": "Wird es der Aura des Mondes ausgesetzt, glühen seine Ringe und es wird von einer mysteriösen.",
    "MurkrowPokedexEntry": "Viele verabscheuen und hassen es, da sie glauben, es bringe Verderben, wenn sie ihm nachts.",
    "SlowkingPlainPokedexEntry": "Als Flegmon in den Kopf gebissen wurde, floss Gift in seinen Kopf und setzte eine gewaltige.",
    "MisdreavusPokedexEntry": "Es liebt Streiche und erschreckt nachts Menschen, indem es heult oder ihnen im Dunkeln.",
    "UnownPokedexEntry": "Seine Form sieht aus wie antike Schrift. Was war zuerst da? Die Sprache oder Icognito?.",
    "WobbuffetPokedexEntry": "Es lebt in der Dunkelheit, um seinen schwarzen Schweif zu verstecken. Es an greift nie zuerst.",
    "GirafarigPokedexEntry": "Sein Schweif hat ein eigenes Gehirn. Achtung!.",
    "PinecoPokedexEntry": "Es sieht aus wie ein Tannenzapfen.",
    "ForretressPokedexEntry": "Es bleibt stets bei seinem Baum.",
    "DunsparcePokedexEntry": "Es gräbt sich mit seinem Schweif in die Erde und baut ein labyrinthartiges Nest.",
    "GligarPokedexEntry": "Es fliegt direkt auf das Gesicht seiner Feinde zu und injiziert ihnen eine Überdosis Gift.",
    "SteelixPokedexEntry": "Es beißt sich mit seinen Kiefern seinen Weg durch Felsen. Es kann auch im Dunkeln sehen.",
    "SnubbullPokedexEntry": "Kleine #mon fliehen beim Anblick seines Gesichts. Frauen aber finden es niedlich.",
    "GranbullPokedexEntry": "Es kann fast jedes #mon vertreiben, indem es sein Maul weit öffnet und seine scharfen.",
    "QwilfishPokedexEntry": "Die kleinen Stacheln an seinem Körper sind aus Schuppen entstanden. Damit injiziert es Gift.",
    "ScizorPokedexEntry": "Sein Körper ist stahlhart.",
    "ShucklePokedexEntry": "Es sammelt Beeren in seiner Schale.",
    "HeracrossPokedexEntry": "Mit seiner herkulischen Kraft kann es Objekte, die hundertmal sein Körpergewicht haben,.",
    "SneaselPokedexEntry": "In seinen Pfoten stecken scharfe Krallen.",
    "TeddiursaPokedexEntry": "Steht der Winter vor der Türe, hortet es Nahrung an vielen verschiedenen, nur ihm bekannten.",
    "UrsaringPokedexEntry": "Trotz seines riesigen Körpers ist es ein guter Kletterer. Es frisst und schläft in Baumkronen.",
    "SlugmaPokedexEntry": "Sein Körper besteht aus Magma.",
    "MagcargoPokedexEntry": "Sein Körper ist heißer als Lava und wogt stets. Manchmal schießen Flammen aus seinem Haus.",
    "SwinubPokedexEntry": "Wenn es etwas Vielversprechendes erschnuppert, dann stürzt es in Windeseile darauf zu.",
    "PiloswinePokedexEntry": "Da sein haariges Fell seine Sicht enorm beeinträchtigt, zu greift es ständig an, um den Gegner.",
    "CorsolaPlainPokedexEntry": "Hält sich lieber in den sauberen Seen im Süden auf.",
    "RemoraidPokedexEntry": "Mit seiner Rückenflosse saugt es sich an der Unterseite eines Mantax fest und lebt von.",
    "OctilleryPokedexEntry": "Beim Beutefang setzt es seine Tentakel ein.",
    "DelibirdPokedexEntry": "Es trägt den ganzen Tag Essen mit sich herum, das es mit Menschen teilt, die in den Bergen.",
    "MantinePokedexEntry": "Zieht elegant durch die Meere und ignoriert dabei Remoraid, die an seinen Flossen haften.",
    "SkarmoryPokedexEntry": "Es wird komplett von einer eisenharten Rüstung geschützt.",
    "HoundourPokedexEntry": "Sie treiben ihre Beute in die Enge und orientieren sich dabei anhand ihres Bellens, das nur.",
    "HoundoomPokedexEntry": "Ist es wütend, spuckt es giftige Flammen. Die Schmerzen der Verbrennungen dauern ewig an.",
    "KingdraPokedexEntry": "Kein anderes Lebewesen kann in den Tiefen existieren, in denen es schläft und so Energie.",
    "PhanpyPokedexEntry": "Trotz seiner geringen Größe ist es stark.",
    "DonphanPokedexEntry": "Je größer und länger die Stoßzähne, desto höher ist ihr Rang in der Herde, doch das dauert.",
    "Porygon2PokedexEntry": "Interstellare Software wurde installiert, sodass dieses #mon sich auch im All bewegen kann.",
    "StantlerPokedexEntry": "Sein gebogenes Geweih generiert via Luftänderung einen Raum, in dem die Wirklichkeit verzerrt.",
    "SmearglePokedexEntry": "Ist es erwachsen, lässt es sich gern von seinen Kameraden Fußabdrücke auf den Rücken setzen.",
    "TyroguePokedexEntry": "Um seine ampfgeist Kampffähigkeiten zu verbessern, tritt es gegen jeden an. Es besitzt großen K-.",
    "HitmontopPokedexEntry": "Lässt du dich von seinen eleganten, anmutigen und tanzartigen Tritten betören, wirst du.",
    "SmoochumPokedexEntry": "Dieses #mon berührt alles mit den Lippen. Diese merken sich, was es mag und nicht mag.",
    "ElekidPokedexEntry": "Wenn es seine Arme kreisen lässt, um Strom zu erzeugen, entstehen zwischen seinen Hörnern.",
    "MagbyPokedexEntry": "Durch seinen Körper fließt magmaartiges Blut. Die °C steigen Körpertemperatur kann auf ca. 600.",
    "MiltankPokedexEntry": "Aufgrund der vielen Nährstoffe stellt seine Milch das ideale Getränk für Kranke und Schwache.",
    "BlisseyPokedexEntry": "Dieses gutherzige #mon pflegt kranke #mon gesund. Es spürt die Traurigkeit anderer Lebewesen.",
    "RaikouPokedexEntry": "Dieses aggressive #mon speichert Energie in seinem Körper und entlädt sie, wenn es über das.",
    "EnteiPokedexEntry": "Man sagt, wenn es brüllt, bricht irgendwo in der Welt ein Vulkan aus.",
    "SuicunePokedexEntry": "Man sagt, es sei die Wiedergeburt des Nordwindes. Es kann verschmutztes Wasser im Nu reinigen.",
    "LarvitarPokedexEntry": "Sie schlüpfen tief unter der Erde und fressen sich durch das Erdreich bis zur Oberfläche.",
    "PupitarPokedexEntry": "Es ist sehr stark und sein Panzer ist steinhart.",
    "TyranitarPokedexEntry": "Bei einem Tobsuchtsanfall zerstört es ganze Gebirge und legt Flüsse trocken.",
    "LugiaPokedexEntry": "Man berichtet, es sei der Wächter der Meere und man habe es im Herzen eines tosenden Sturmes.",
    "HoOhPokedexEntry": "Es wird sich dem Trainer offenbaren, der reinen Herzens ist, und ihm seine bunten Schwingen.",
    "CelebiPokedexEntry": "Es kann durch die Zeit reisen, aber es erscheint nur zu friedlichen Zeiten.",
    "AzurillPokedexEntry": "Sein Schweif enthält Nährstoffe fürs Wachstum. Es spielt, indem es auf dem Schweif hüpft.",
    "WynautPokedexEntry": "Es bewegt sich meist im Rudel. Einzelne drücken sich zusammen, um ihren Mut zu stärken.",
    "AmbipomPokedexEntry": "Geteilte Schweife sind so geschickt, dass Ambidiffel seine Hände kaum noch nutzt.",
    "MismagiusPokedexEntry": "Seine Rufe klingen wie Beschwörungen zur Qual des Gegners. Es erscheint unerwartet.",
    "HonchkrowPokedexEntry": "Es ist von Natur aus gnadenlos und verzeiht Fehler seiner Kramurx-Anhänger nie.",
    "BonslyPokedexEntry": "Es bevorzugt trockene Luft. Beim Feuchtigkeitsausgleich tropft wassertropfenartige Flüssigkeit.",
    "MimeJrPokedexEntry": "Es ahmt Mimik und Gesten nach, um die Gefühle anderer zu verstehen.",
    "HappinyPokedexEntry": "Es trägt einen runden, eiförmigen Stein im Bauchbeutel und schenkt ihn Freunden.",
    "MunchlaxPokedexEntry": "In seiner Gier zu fressen vergisst es das Futter, das es im Fell versteckt hat.",
    "MantykePokedexEntry": "Man organisiert Touren, um dieses #mon mit Remoraid über die Wellen gleiten zu sehen.",
    "WeavilePokedexEntry": "Es lebt in Schneeregionen und ritzt mit Krallen Muster in Bäume als Signal.",
    "MagnezonePokedexEntry": "Es entwickelte sich durch ein spezielles Magnetfeld. Drei Einheiten erzeugen Magnetismus.",
    "LickilickyPokedexEntry": "Die lange Zunge ist stets mit Speichel benetzt. Er enthält ein betäubendes Lösungsmittel.",
    "RhyperiorPokedexEntry": "Aus Löchern in seinen Handflächen schießt es Georok. Sein Panzer hält Vulkanausbrüche stand.",
    "TangrowthPokedexEntry": "Es fängt Beute mit aus Ranken gewachsenen Armen. Verliert es welche, stört das es nicht.",
    "ElectivirePokedexEntry": "Es drückt die Schweifspitzen an den Gegner und entlädt über 20000 Volt.",
    "MagmortarPokedexEntry": "Viele Fabriken nutzen noch die Flammen von Magbrust zur Metallverarbeitung.",
    "TogekissPokedexEntry": "Es segnet Menschen, die einander respektieren und unnötigen Streit meiden.",
    "YanmegaPokedexEntry": "Seine Kieferkraft ist enorm. Im Flug beißt es Gegner im Vorbeisausen auseinander.",
    "LeafeonPokedexEntry": "Wie eine Pflanze nutzt es Photosynthese und ist stets von klarer Luft umgeben.",
    "GlaceonPokedexEntry": "Es erzeugt kleine Eiskristalle, indem es die Temperatur der Umgebungsluft senkt.",
    "GliscorPokedexEntry": "Sein Flug ist lautlos. Mit dem langen Schweif trägt es Beute fort, dann greifen die Fangzähne.",
    "MamoswinePokedexEntry": "Seine Stoßzähne bestehen aus Eis. Nach der Eiszeit wurde die Population kleiner.",
    "PorygonZPokedexEntry": "Sein Programm wurde für fremde Dimensionen geändert. Es funktionierte nicht wie geplant.",
    "SylveonPokedexEntry": "Es wickelt bandartige Fühler um den Arm seines geliebten Trainers und geht mit ihm.",
    "PerrserkerPokedexEntry": "Nach vielen Kämpfen entwickelte es gefährliche Krallen, die wie Dolche wirken.",
    "CursolaPokedexEntry": "Vorsicht vor dem ectoplasmischen Körper um seine Seele. Berührung lässt einen erstarren.",
    "SirfetchDPokedexEntry": "Nach dem Abwehren mit dem harten Blattschild schlägt es mit dem scharfen Lauch zurück.",
    "MrRimePokedexEntry": "Es ist sehr begabt im Stepptanz und schwingt seinen Eisstock im Takt eleganter Bewegungen.",
    "WyrdeerPokedexEntry": "Das Bartfell hält Wärme gut und ist ein wertvoller Stoff für Winterkleidung.",
    "KleavorPokedexEntry": "Es fällt mit groben Äxten hohe Bäume und schützt sich mit hartem Stein.",
    "UrsalunaPokedexEntry": "Dieses #mon hat einen kräftigen Körper und kann Torf nach Belieben formen.",
    "SneaslerPokedexEntry": "Es hat virulentes Gift und starke Körperkraft. Es lebt lieber allein als im Rudel.",
    "OverqwilPokedexEntry": "Stacheln und wildes Temperament brachten ihm den Namen Meeresungeheuer. Es schlürft Gift.",
    "DudunsparcePokedexEntry": "Mit dem harten Schweif bohrt es Nester in tiefes Gestein. Sie können über zehn Kilometer reichen.",
    "FarigirafPokedexEntry": "Da Hirnwellen von Kopf und Schweif synchron sind, ist seine Psycho-Kraft zehnmal stärker.",
    "ClodsirePokedexEntry": "Wird es angegriffen, stößt es dicke Stacheln aus dem Körper. Ein riskanter Schachzug.",
    "AnnihilapePokedexEntry": "Als seine Wut einen kritischen Punkt überschritt, erlangte es Kraft jenseits seines Körpers.",
    "GyaradosRedPokedexEntry": "Durch die rasche Zwangsentwicklung behielt dieses Garados die roten Schuppen eines Karpador.",
    "MewtwoArmoredPokedexEntry": "Mit verstärkter Verteidigung und verstärkten Psycho-Angriffen durch die Rüstung ist Mewtu unaufhaltsam.",
    "RattataAlolanPokedexEntry": "Es interessiert sich nur für Frisches. Nimmst du es einkaufen, hilft es bei der Auswahl.",
    "RaticateAlolanPokedexEntry": "Es lässt Rattfratz-Untergebene Nahrung sammeln und frisst nur das Beste.",
    "RaichuAlolanPokedexEntry": "Reibt man seine Wangen, verströmt es einen süßen Duft. Man bekommt aber auch einen leichten Schock.",
    "SandshrewAlolanPokedexEntry": "Es lebt auf Schneebergen. Sein Stahlpanzer ist so hart, dass es sich nicht einrollen kann.",
    "SandslashAlolanPokedexEntry": "Viele klettern auf Schneeberge, um die Eiszapfen dieses #mon im Morgenlicht zu sehen.",
    "VulpixAlolanPokedexEntry": "Betrachtet man seine lockigen Haare im Mikroskop, sieht man kleine Eiskristalle entstehen.",
    "NinetalesAlolanPokedexEntry": "Es führt Menschen den Berg hinab, damit sie schnell gehen und das Gebiet verlassen.",
    "DiglettAlolanPokedexEntry": "Das metallreiche Gestein seiner Heimat ließ Stahlbarthaare auf seinem Kopf wachsen.",
    "DugtrioAlolanPokedexEntry": "Seine metallischen Barthaare sind schwer, daher ist es langsam, kann aber durch Fels graben.",
    "MeowthAlolanPokedexEntry": "Hochintelligent und stolz, ist es berühmt schwer zu zähmen. Das macht es auch beliebt.",
    "GrimerAlolanPokedexEntry": "Ein zur Müllbeseitigung eingesetztes Sleima entwickelte sich zu dieser Form.",
    "MukAlolanPokedexEntry": "Sleimoks Färbung wird lebhafter, je mehr es von seinem Lieblingsgericht Müll frisst.",
    "ExeggutorAlolanPokedexEntry": "Es schwingt den langen Hals wie eine Peitsche gegen Gegner. Dadurch wird auch es selbst schwindelig.",
    "MarowakAlolanPokedexEntry": "Es entzündet den Knochen in der Hand und tanzt nachts, um gefallene Gefährten zu betrauern.",
    "MeowthGalarianPokedexEntry": "Diese mutigen #mon haben Münzen auf der Stirn. Härtere Münzen bringen mehr Respekt.",
    "PersianAlolanPokedexEntry": "Es hat das edelste Fell. Das Wellen im Kampf hat eine eigene Schönheit.",
    "GeodudeAlolanPokedexEntry": "Sein Körper ist magnetischer Stein. Eisensand haftet an den stärksten magnetischen Stellen.",
    "GravelerAlolanPokedexEntry": "Sein ganzer Körper ist elektrisch geladen durch die Steine, die es frisst. Es ist sehr jähzornig.",
    "GolemAlolanPokedexEntry": "Es schießt elektrisch geladene Felsen. Schrammt man nur daran, wird man betäubt.",
    "PonytaGalarianPokedexEntry": "Es blickt dir in die Augen und liest dein Herz. Findet es Böses, zieht es sich zurück.",
    "RapidashGalarianPokedexEntry": "Ein Psycho-Angriff aus seinem Horn kann selbst dickes Blech durchschlagen.",
    "SlowpokeGalarianPokedexEntry": "Normalerweise träumerisch, wird sein Blick manchmal plötzlich scharf. Vielleicht liegt es am Futter.",
    "SlowbroGalarianPokedexEntry": "Ein Muschas-Biss löste eine chemische Reaktion aus und machte Lahmus zu einem Gift-#mon.",
    "FarfetchDGalarianPokedexEntry": "Diese besonderen Porenta sind tapfere Krieger und kämpfen mit dicken, festen Lauchstangen.",
    "WeezingGalarianPokedexEntry": "Es nimmt verschmutzte Luftpartikel auf. Statt Kot auszuscheiden, stößt es saubere Luft aus.",
    "MrMimeGalarianPokedexEntry": "Es kann Kälte von den Fußsohlen abgeben und tanzt den ganzen Tag auf gefrorenem Boden.",
    "ArticunoGalarianPokedexEntry": "Als Arktos bekannt, feuert dieses #mon Strahlen ab, die Gegner wie erstarrt lähmen.",
    "ZapdosGalarianPokedexEntry": "Wenn sich seine Federn reiben, entsteht ein Knistern wie elektrische Entladungen.",
    "MoltresGalarianPokedexEntry": "Die finstere Aura um dieses #mon, die wie Feuer lodert, gab ihm den Namen Lavados.",
    "SlowkingGalarianPokedexEntry": "Gift und der Schock der Entwicklung ließen Muschas die Kontrolle über Laschoking übernehmen.",
    "CorsolaGalarianPokedexEntry": "Plötzlicher Klimawandel löschte dieses #mon aus. Es saugt über Äste fremde Lebenskraft.",
    "GrowlitheHisuianPokedexEntry": "Sie patrouillieren zu zweit ihr Revier. Ihr Fell enthält vulkanisches Gestein.",
    "ArcanineHisuianPokedexEntry": "Trotz seiner Masse fintiert es geschickt und führt Gegner beim Tanz vorbei.",
    "VoltorbHisuianPokedexEntry": "Wird es aufgeregt, entlädt es Strom aus dem Bauch und lacht dabei.",
    "ElectrodeHisuianPokedexEntry": "Das Gewebe an seiner Oberfläche ähnelt stark einer Aprikoko.",
    "TyphlosionHisuianPokedexEntry": "Man sagt, es reinige verlorene Seelen mit seinen Flammen und geleite sie ins Jenseits.",
    "QwilfishHisuianPokedexEntry": "Fischer hassen es, weil es Gift aus Stacheln spritzt und alles besprüht.",
    "SneaselHisuianPokedexEntry": "Seine robusten Krallen eignen sich fürs Klettern. Sie tropfen Gift in die Beute.",
    "WooperPaldeanPokedexEntry": "Sie gehen zu dritt oder viert und helfen einander beim Gang durch gefährliche Sümpfe.",
    "TaurosPaldeanPokedexEntry": "Die Kampfrasse kämpft aus nächster Nähe und trifft mit kurzen Hörnern Schwachstellen.",
    "TaurosPaldeanFirePokedexEntry": "Die Hörner der Flammenrasse erreichen über 1800 Grad. Aufstoß verursacht Brandwunden.",
    "TaurosPaldeanWaterPokedexEntry": "Die Aqua-Rasse schwimmt, indem es Wasser aus den Hörnern spritzt. Hoher Körperfettanteil lässt es schweben.",
    "UrsalunaBloodmoonPokedexEntry": "Mit dem linken Auge sieht es im Dunkeln und schützt sich mit hartem Schlamm wie Eisen.",
}

CATEGORIES = {
    "BulbasaurPokedexEntry": "Samen",
    "IvysaurPokedexEntry": "Samen",
    "VenusaurPokedexEntry": "Samen",
    "CharmanderPokedexEntry": "Eidechse",
    "CharmeleonPokedexEntry": "Flamme",
    "CharizardPokedexEntry": "Flamme",
    "SquirtlePokedexEntry": "Minikröte",
    "WartortlePokedexEntry": "Schildkröte",
    "BlastoisePokedexEntry": ["Panzerweich", "Panzer"],
    "CaterpiePokedexEntry": "Wurm",
    "MetapodPokedexEntry": "Kokon",
    "ButterfreePokedexEntry": "Falter",
    "WeedlePokedexEntry": "Raupe",
    "KakunaPokedexEntry": "Kokon",
    "BeedrillPokedexEntry": "Giftbiene",
    "PidgeyPokedexEntry": "Minivogel",
    "PidgeottoPokedexEntry": "Vogel",
    "PidgeotPokedexEntry": "Vogel",
    "RattataPlainPokedexEntry": "Ratte",
    "RaticatePlainPokedexEntry": "Ratte",
    "SpearowPokedexEntry": "Minivogel",
    "FearowPokedexEntry": "Pick",
    "EkansPokedexEntry": "Schlange",
    "ArbokPokedexEntry": "Natter",
    "PikachuPokedexEntry": "Maus",
    "RaichuPlainPokedexEntry": "Maus",
    "SandshrewPlainPokedexEntry": "Maus",
    "SandslashPlainPokedexEntry": "Maus",
    "NidoranFPokedexEntry": "Giftstachel",
    "NidorinaPokedexEntry": "Giftstachel",
    "NidoqueenPokedexEntry": "Bohrer",
    "NidoranMPokedexEntry": "Giftstachel",
    "NidorinoPokedexEntry": "Giftstachel",
    "NidokingPokedexEntry": "Bohrer",
    "ClefairyPokedexEntry": "Fee",
    "ClefablePokedexEntry": "Fee",
    "VulpixPlainPokedexEntry": "Fuchs",
    "NinetalesPlainPokedexEntry": "Fuchs",
    "JigglypuffPokedexEntry": "Ballon",
    "WigglytuffPokedexEntry": "Ballon",
    "ZubatPokedexEntry": "Fledermaus",
    "GolbatPokedexEntry": "Fledermaus",
    "OddishPokedexEntry": "Unkraut",
    "GloomPokedexEntry": "Unkraut",
    "VileplumePokedexEntry": "Blume",
    "ParasPokedexEntry": "Pilz",
    "ParasectPokedexEntry": "Pilz",
    "VenonatPokedexEntry": "Insekt",
    "VenomothPokedexEntry": "Giftmotte",
    "DiglettPlainPokedexEntry": "Maulwurf",
    "DugtrioPlainPokedexEntry": "Maulwurf",
    "MeowthPlainPokedexEntry": "Katze",
    "PersianPlainPokedexEntry": "Samtpfote",
    "PsyduckPokedexEntry": "Ente",
    "GolduckPokedexEntry": "Ente",
    "MankeyPokedexEntry": "Schweinaffe",
    "PrimeapePokedexEntry": "Schweinaffe",
    "GrowlithePokedexEntry": "Welpe",
    "ArcaninePokedexEntry": "Legendär",
    "PoliwagPokedexEntry": "Quappe",
    "PoliwhirlPokedexEntry": "Quappe",
    "PoliwrathPokedexEntry": "Quappe",
    "AbraPokedexEntry": "Psi",
    "KadabraPokedexEntry": "Psi",
    "AlakazamPokedexEntry": "Psi",
    "MachopPokedexEntry": "Kraftprotz",
    "MachokePokedexEntry": "Kraftprotz",
    "MachampPokedexEntry": "Kraftprotz",
    "BellsproutPokedexEntry": "Blume",
    "WeepinbellPokedexEntry": "Fliegenfalle",
    "VictreebelPokedexEntry": "Fliegenfalle",
    "TentacoolPokedexEntry": "Qualle",
    "TentacruelPokedexEntry": "Qualle",
    "GeodudePlainPokedexEntry": "Felsen",
    "GravelerPlainPokedexEntry": "Felsen",
    "GolemPlainPokedexEntry": "Gewicht",
    "PonytaPlainPokedexEntry": "Feuerpferd",
    "RapidashPlainPokedexEntry": "Feuerpferd",
    "SlowpokePlainPokedexEntry": "Dösig",
    "SlowbroPlainPokedexEntry": ["Einsiedler", "Schmarotzer"],
    "MagnemitePokedexEntry": "Magnet",
    "MagnetonPokedexEntry": "Magnet",
    "FarfetchDPlainPokedexEntry": "Entoron",
    "DoduoPokedexEntry": "Duovogel",
    "DodrioPokedexEntry": "Triovogel",
    "SeelPokedexEntry": "Seehund",
    "DewgongPokedexEntry": "Seehund",
    "GrimerPlainPokedexEntry": "Schlamm",
    "MukPlainPokedexEntry": "Schlamm",
    "ShellderPokedexEntry": "Muschel",
    "CloysterPokedexEntry": "Muschel",
    "GastlyPokedexEntry": "Gas",
    "HaunterPokedexEntry": "Gas",
    "GengarPokedexEntry": "Schatten",
    "OnixPokedexEntry": "Felsenschlange",
    "DrowzeePokedexEntry": "Hypnose",
    "HypnoPokedexEntry": "Hypnose",
    "KrabbyPokedexEntry": "Flusskrabbe",
    "KinglerPokedexEntry": "Schere",
    "VoltorbPokedexEntry": "Ball",
    "ElectrodePokedexEntry": "Ball",
    "ExeggcutePokedexEntry": "Ei",
    "ExeggutorPlainPokedexEntry": "Kokosnuss",
    "CubonePokedexEntry": "Einsam",
    "MarowakPlainPokedexEntry": "Knochenhüter",
    "HitmonleePokedexEntry": "Kicker",
    "HitmonchanPokedexEntry": "Puncher",
    "LickitungPokedexEntry": "Schlecker",
    "KoffingPokedexEntry": "Giftgas",
    "WeezingPlainPokedexEntry": "Giftgas",
    "RhyhornPokedexEntry": "Stachel",
    "RhydonPokedexEntry": "Bohrer",
    "ChanseyPokedexEntry": "Ei",
    "TangelaPokedexEntry": "Kletterer",
    "KangaskhanPokedexEntry": "Mutter",
    "HorseaPokedexEntry": "Drache",
    "SeadraPokedexEntry": "Drache",
    "GoldeenPokedexEntry": "Goldfisch",
    "SeakingPokedexEntry": "Goldfisch",
    "StaryuPokedexEntry": "Stern",
    "StarmiePokedexEntry": "Mysterium",
    "MrMimePlainPokedexEntry": "Barriere",
    "ScytherPokedexEntry": "Sichelkäfer",
    "JynxPokedexEntry": "Humanoid",
    "ElectabuzzPokedexEntry": "Elektro",
    "MagmarPokedexEntry": "Feuer",
    "PinsirPokedexEntry": "Hirschkäfer",
    "TaurosPlainPokedexEntry": "Wildbulle",
    "MagikarpPokedexEntry": "Fisch",
    "GyaradosPlainPokedexEntry": "Brutal",
    "LaprasPokedexEntry": "Transport",
    "DittoPokedexEntry": "Transform",
    "EeveePokedexEntry": "Evolution",
    "VaporeonPokedexEntry": "Blubber",
    "JolteonPokedexEntry": "Blitz",
    "FlareonPokedexEntry": "Flamme",
    "PorygonPokedexEntry": "Virtuell",
    "OmanytePokedexEntry": "Spirale",
    "OmastarPokedexEntry": "Spirale",
    "KabutoPokedexEntry": "Panzerweich",
    "KabutopsPokedexEntry": "Panzerweich",
    "AerodactylPokedexEntry": "Fossil",
    "SnorlaxPokedexEntry": "Schläfer",
    "ArticunoPlainPokedexEntry": "Gefrier",
    "ZapdosPlainPokedexEntry": "Elektro",
    "MoltresPlainPokedexEntry": "Flamme",
    "DratiniPokedexEntry": "Drache",
    "DragonairPokedexEntry": "Drache",
    "DragonitePokedexEntry": "Drache",
    "MewtwoPlainPokedexEntry": "Genmutant",
    "MewPokedexEntry": "Neuart",
    "ChikoritaPokedexEntry": "Laub",
    "BayleefPokedexEntry": "Laub",
    "MeganiumPokedexEntry": "Kraut",
    "CyndaquilPokedexEntry": "Feuermaus",
    "QuilavaPokedexEntry": "Vulkan",
    "TyphlosionPlainPokedexEntry": "Vulkan",
    "TotodilePokedexEntry": "Großmaul",
    "CroconawPokedexEntry": "Großmaul",
    "FeraligatrPokedexEntry": "Großmaul",
    "SentretPokedexEntry": "Späher",
    "FurretPokedexEntry": "Langgliedrig",
    "HoothootPokedexEntry": "Eule",
    "NoctowlPokedexEntry": "Eule",
    "LedybaPokedexEntry": "Fünfstern",
    "LedianPokedexEntry": "Fünfstern",
    "SpinarakPokedexEntry": "Faden",
    "AriadosPokedexEntry": "Langbein",
    "CrobatPokedexEntry": "Fledermaus",
    "ChinchouPokedexEntry": "Laternen",
    "LanturnPokedexEntry": "Leuchte",
    "PichuPokedexEntry": "Minimaus",
    "CleffaPokedexEntry": "Stern",
    "IgglybuffPokedexEntry": "Ballon",
    "TogepiPokedexEntry": "Stachelball",
    "TogeticPokedexEntry": "Freude",
    "NatuPokedexEntry": "Spatz",
    "XatuPokedexEntry": "Mystik",
    "MareepPokedexEntry": "Wolle",
    "FlaaffyPokedexEntry": "Wolle",
    "AmpharosPokedexEntry": "Leuchte",
    "BellossomPokedexEntry": "Blume",
    "MarillPokedexEntry": "Aquamaus",
    "AzumarillPokedexEntry": "Aquahase",
    "SudowoodoPokedexEntry": "Nachahmer",
    "PolitoedPokedexEntry": "Frosch",
    "HoppipPokedexEntry": "Löwenzahn",
    "SkiploomPokedexEntry": "Löwenzahn",
    "JumpluffPokedexEntry": "Löwenzahn",
    "AipomPokedexEntry": "Langschweif",
    "SunkernPokedexEntry": "Samen",
    "SunfloraPokedexEntry": "Sonne",
    "YanmaPokedexEntry": "Libelle",
    "WooperPlainPokedexEntry": "Fisch",
    "QuagsirePokedexEntry": "Fisch",
    "EspeonPokedexEntry": "Sonne",
    "UmbreonPokedexEntry": "Mondlicht",
    "MurkrowPokedexEntry": "Finsternis",
    "SlowkingPlainPokedexEntry": "König",
    "MisdreavusPokedexEntry": "Kreischer",
    "UnownPokedexEntry": "Symbol",
    "WobbuffetPokedexEntry": "Geduldig",
    "GirafarigPokedexEntry": "Langhals",
    "PinecoPokedexEntry": "Beutel",
    "ForretressPokedexEntry": "Beutel",
    "DunsparcePokedexEntry": "Landraupe",
    "GligarPokedexEntry": "Skorpion",
    "SteelixPokedexEntry": "Eisen",
    "SnubbullPokedexEntry": "Fee",
    "GranbullPokedexEntry": "Fee",
    "QwilfishPokedexEntry": "Ballon",
    "ScizorPokedexEntry": "Schere",
    "ShucklePokedexEntry": "Schimmel",
    "HeracrossPokedexEntry": "Horn",
    "SneaselPokedexEntry": "Scharfklaue",
    "TeddiursaPokedexEntry": "Jungbär",
    "UrsaringPokedexEntry": "Winterschlaf",
    "SlugmaPokedexEntry": "Lava",
    "MagcargoPokedexEntry": "Lava",
    "SwinubPokedexEntry": "Schwein",
    "PiloswinePokedexEntry": "Wildschwein",
    "CorsolaPlainPokedexEntry": "Koralle",
    "RemoraidPokedexEntry": "Jet",
    "OctilleryPokedexEntry": "Jet",
    "DelibirdPokedexEntry": "Kurier",
    "MantinePokedexEntry": "Drachen",
    "SkarmoryPokedexEntry": "Panzer",
    "HoundourPokedexEntry": "Dunkel",
    "HoundoomPokedexEntry": "Dunkel",
    "KingdraPokedexEntry": "Drache",
    "PhanpyPokedexEntry": "Rüssel",
    "DonphanPokedexEntry": "Panzer",
    "Porygon2PokedexEntry": "Virtuell",
    "StantlerPokedexEntry": "Großhorn",
    "SmearglePokedexEntry": "Maler",
    "TyroguePokedexEntry": "Rauf",
    "HitmontopPokedexEntry": "Radler",
    "SmoochumPokedexEntry": "Kuss",
    "ElekidPokedexEntry": "Elektro",
    "MagbyPokedexEntry": "Glut",
    "MiltankPokedexEntry": "Milchkuh",
    "BlisseyPokedexEntry": "Freude",
    "RaikouPokedexEntry": "Donner",
    "EnteiPokedexEntry": "Vulkan",
    "SuicunePokedexEntry": "Polarlicht",
    "LarvitarPokedexEntry": "Steinhaut",
    "PupitarPokedexEntry": "Rüstepanzer",
    "TyranitarPokedexEntry": "Panzer",
    "LugiaPokedexEntry": "Tauchen",
    "HoOhPokedexEntry": "Regenbogen",
    "CelebiPokedexEntry": "Zeitreise",
    "AzurillPokedexEntry": "Tüpfel",
    "WynautPokedexEntry": "Strahl",
    "AmbipomPokedexEntry": "Langschweif",
    "MismagiusPokedexEntry": "Magie",
    "HonchkrowPokedexEntry": "Don",
    "BonslyPokedexEntry": "Bonsai",
    "MimeJrPokedexEntry": "Mime",
    "HappinyPokedexEntry": "Spielhaus",
    "MunchlaxPokedexEntry": "Vielfraß",
    "MantykePokedexEntry": "Drachen",
    "WeavilePokedexEntry": "Scharfklaue",
    "MagnezonePokedexEntry": "Magnetzone",
    "LickilickyPokedexEntry": "Schlecker",
    "RhyperiorPokedexEntry": "Bohrer",
    "TangrowthPokedexEntry": "Kletterer",
    "ElectivirePokedexEntry": "Donnerkeil",
    "MagmortarPokedexEntry": "Detonator",
    "TogekissPokedexEntry": "Festtag",
    "YanmegaPokedexEntry": "Libelle",
    "LeafeonPokedexEntry": "Blattgrün",
    "GlaceonPokedexEntry": "Neuschnee",
    "GliscorPokedexEntry": "FangScorpio",
    "MamoswinePokedexEntry": "Doppelstoßzahn",
    "PorygonZPokedexEntry": "Virtuell",
    "SylveonPokedexEntry": "Band",
    "PerrserkerPokedexEntry": "Wikinger",
    "CursolaPokedexEntry": "Koralle",
    "SirfetchDPokedexEntry": "Entoron",
    "MrRimePokedexEntry": "Komiker",
    "WyrdeerPokedexEntry": "Großhorn",
    "KleavorPokedexEntry": "Axt",
    "UrsalunaPokedexEntry": "Torf",
    "SneaslerPokedexEntry": "Freikletterer",
    "OverqwilPokedexEntry": "Stachel",
    "DudunsparcePokedexEntry": "Landraupe",
    "FarigirafPokedexEntry": "Langhals",
    "ClodsirePokedexEntry": "Stachler",
    "AnnihilapePokedexEntry": "Wutaffe",
    "GyaradosRedPokedexEntry": "Brutal",
    "MewtwoArmoredPokedexEntry": "Genmutant",
    "RattataAlolanPokedexEntry": "Maus",
    "RaticateAlolanPokedexEntry": "Maus",
    "RaichuAlolanPokedexEntry": "Maus",
    "SandshrewAlolanPokedexEntry": "Maus",
    "SandslashAlolanPokedexEntry": "Maus",
    "VulpixAlolanPokedexEntry": "Fuchs",
    "NinetalesAlolanPokedexEntry": "Fuchs",
    "DiglettAlolanPokedexEntry": "Maulwurf",
    "DugtrioAlolanPokedexEntry": "Maulwurf",
    "MeowthAlolanPokedexEntry": "Katze",
    "GrimerAlolanPokedexEntry": "Schlamm",
    "MukAlolanPokedexEntry": "Schlamm",
    "ExeggutorAlolanPokedexEntry": "Kokosnuss",
    "MarowakAlolanPokedexEntry": "Knochenhüter",
    "MeowthGalarianPokedexEntry": "Katze",
    "PersianAlolanPokedexEntry": "Samtpfote",
    "GeodudeAlolanPokedexEntry": "Felsen",
    "GravelerAlolanPokedexEntry": "Felsen",
    "GolemAlolanPokedexEntry": "Gewicht",
    "PonytaGalarianPokedexEntry": "Einhorn",
    "RapidashGalarianPokedexEntry": "Einhorn",
    "SlowpokeGalarianPokedexEntry": "Dösig",
    "SlowbroGalarianPokedexEntry": ["Einsiedler", "Schmarotzer"],
    "FarfetchDGalarianPokedexEntry": "Entoron",
    "WeezingGalarianPokedexEntry": "Giftgas",
    "MrMimeGalarianPokedexEntry": "Tänzer",
    "ArticunoGalarianPokedexEntry": "Grausam",
    "ZapdosGalarianPokedexEntry": "Starkbein",
    "MoltresGalarianPokedexEntry": "Unheil",
    "SlowkingGalarianPokedexEntry": "Hexenmeister",
    "CorsolaGalarianPokedexEntry": "Koralle",
    "GrowlitheHisuianPokedexEntry": "Späher",
    "ArcanineHisuianPokedexEntry": "Legendär",
    "VoltorbHisuianPokedexEntry": "Kugel",
    "ElectrodeHisuianPokedexEntry": "Kugel",
    "TyphlosionHisuianPokedexEntry": "Geisterflamme",
    "QwilfishHisuianPokedexEntry": "Ballon",
    "SneaselHisuianPokedexEntry": "Scharfklaue",
    "WooperPaldeanPokedexEntry": "Giftfisch",
    "TaurosPaldeanPokedexEntry": "Wildbulle",
    "TaurosPaldeanFirePokedexEntry": "Wildbulle",
    "TaurosPaldeanWaterPokedexEntry": "Wildbulle",
    "UrsalunaBloodmoonPokedexEntry": "Torf",
}
