# German Pokedex entry texts keyed by label name
TEXT = {
"BulbasaurPokedexEntry": "Solange es jung ist, nutzt es Nährstoffe aus den Samen auf seinem Rücken zum Wachsen.",
"IvysaurPokedexEntry": "Die Knospe auf seinem Rücken wächst und nimmt Nährstoffe auf. Beim Aufblühen verströmt sie einen angenehmen Duft.",
"VenusaurPokedexEntry": "Wärmt es sich und nimmt Sonnenlicht auf, verströmen seine Blüten einen angenehmen Duft.",
"CharmanderPokedexEntry": "Ist es gesund, brennt die Flamme an seiner Schwanzspitze kräftig, selbst wenn es etwas nass wird.",
"CharmeleonPokedexEntry": "Wird es im Kampf wütend, stößt es heftige Flammen aus und verbrennt damit seine Umgebung.",
"CharizardPokedexEntry": "Mit seinen Flügeln fliegt es hoch. Die Feuertemperatur steigt mit seiner Kampferfahrung.",
"SquirtlePokedexEntry": "Fühlt es sich bedroht, zieht es die Beine in seinen Panzer und spritzt Wasser aus dem Mund.",
"WartortlePokedexEntry": "Sein langer, behaarter Schweif ist ein Symbol für Langlebigkeit und macht es bei älteren Menschen beliebt.",
"BlastoisePokedexEntry": "Es pflanzt die Füße fest auf den Boden, bevor es Wasser aus den Düsen auf seinem Rücken abschießt.",
"CaterpiePokedexEntry": "Es kriecht in Blätterwerk, wo es sich unter gleichfarbigen Blättern tarnt.",
"MetapodPokedexEntry": "Dies ist seine Vorstufe. In diesem Stadium kann es nur erstarren und bleibt regungslos, um Angriffen auszuweichen.",
"ButterfreePokedexEntry": "Es flattert von Blume zu Blume und sammelt Nektar. Es kann sogar weit entfernte blühende Blumen erkennen.",
"WeedlePokedexEntry": "Der Stachel auf seinem Kopf sondert ein starkes Gift ab. Es nutzt diesen giftigen Stachel zur Verteidigung.",
"KakunaPokedexEntry": "Es ist kaum bewegungsfähig und lehnt sich an starke Bäume, während es auf seine Entwicklung wartet.",
"BeedrillPokedexEntry": "Es besiegt Beute mit scharfen, giftigen Stacheln und bringt sie in sein Nest als Nahrung.",
"PidgeyPokedexEntry": "Es schlägt schnell mit den Flügeln im Gras und wirbelt Staub auf, um Insektenbeute hervorzulocken.",
"PidgeottoPokedexEntry": "Es fliegt langsam im Kreis und hält dabei Ausschau nach Beute.",
"PidgeotPokedexEntry": "Dieses #mon fliegt mit Mach-2-Geschwindigkeit auf Beutejagd. Seine großen Krallen gelten als furchtbare Waffen.",
"RattataPlainPokedexEntry": "Die enorme Vitalität dieses #mon erlaubt es ihm, überall zu leben. Es vermehrt sich auch sehr schnell.",
"RaticatePlainPokedexEntry": "Die Schwimmhäute an seinen Hinterbeinen ermöglichen es ihm, Flüsse zu überqueren. Es sucht weit nach Nahrung.",
"SpearowPokedexEntry": "Zum Schutz seines Reviers fliegt es unaufhörlich umher und gibt hohe Schreie von sich.",
"FearowPokedexEntry": "Es greift mit seinem langen Schnabel an. Seine Reichweite ist überraschend groß, daher ist Vorsicht geboten.",
"EkansPokedexEntry": "Es züngelt mit der Zungenspitze, um den Geruch von Beute zu erschnüffern, und schluckt sie dann im Ganzen.",
"ArbokPokedexEntry": "Um Gegner einzuschüchtern, breitet es die Brust weit und stößt unheimliche Laute aus seinem Maul.",
"PikachuPokedexEntry": "Wenn es wütend ist, entlädt es sofort die in den Backentaschen gespeicherte Energie.",
"RaichuPlainPokedexEntry": "Sind seine elektrischen Backentaschen leer, hebt es den Schweif, um Elektrizität aus der Luft zu sammeln.",
"SandshrewPlainPokedexEntry": "Es bevorzugt trockene, sandige Orte, da es den Sand zum Schutz nutzt, wenn es bedroht wird.",
"SandslashPlainPokedexEntry": "Es kann gut klettern, rollt sich zu einem stacheligen Ball und greift Gegner von oben an.",
"NidoranFPokedexEntry": "Klein und sehr fügsam, schützt es sich mit seinem kleinen, giftigen Horn, wenn es angegriffen wird.",
"NidorinaPokedexEntry": "Es hat ein sanftes Wesen. Wird es bedroht, richtet es die Stacheln über seinem ganzen Körper auf.",
"NidoqueenPokedexEntry": "Die harten Schuppen, die seinen starken Körper bedecken, bieten ausgezeichneten Schutz vor jedem Angriff.",
"NidoranMPokedexEntry": "Es bewegt ständig seine großen Ohren in viele Richtungen, um Gefahr sofort zu erkennen.",
"NidorinoPokedexEntry": "Es ist leicht reizbar und stößt mit seinem Horn an, sobald es einen Angreifer bemerkt.",
"NidokingPokedexEntry": "Es greift mit Armen, Beinen und Schweif kraftvoll an. Nahkampf ist seine Spezialität.",
"ClefairyPokedexEntry": "Obwohl selten gesehen, ist es in Vollmondnächten aus unerfindlichen Gründen leichter zu entdecken.",
"ClefablePokedexEntry": "Man sagt, es lebe in stillen, abgelegenen Bergen und habe eine starke Abneigung, gesehen zu werden.",
"VulpixPlainPokedexEntry": "Mit wachsendem Körper werden seine sechs warmen Schweife schöner und ihr Fell luxuriöser.",
"NinetalesPlainPokedexEntry": "Man sagt, es lebe tausend Jahre und jeder seiner Schweife sei mit übernatürlicher Kraft beladen.",
"JigglypuffPokedexEntry": "Es rollt mit den runden Augen und singt ein beruhigendes Schlaflied. Wer es hört, schläft ein.",
"WigglytuffPokedexEntry": "Das flauschige Fell auf seinem Körper fühlt sich so gut an, dass man nicht aufhören kann, es zu streicheln.",
"ZubatPokedexEntry": "Tagsüber versammelt es sich mit anderen und hängt an Decken alter Gebäude und Höhlen.",
"GolbatPokedexEntry": "Wie dick auch immer die Haut des Opfers sein mag, es durchbohrt sie mit scharfen Fangzähnen und trinkt Blut.",
"OddishPokedexEntry": "Tagsüber hält es sich kühl unter der Erde, um die Sonne zu meiden. Es wächst beim Baden im Mondlicht.",
"GloomPokedexEntry": "Der Geruch seines sirupartigen Speichels und der Blütenpollen ist so übel, dass Gegner ohnmächtig werden können.",
"VileplumePokedexEntry": "Durch Schütteln seiner großen Blütenblätter verstreut es giftigen Pollen und färbt die Luft gelb.",
"ParasPokedexEntry": "Der Tochukaso auf dem Rücken dieses #mon befiehlt ihm, Saft aus Baumstämmen zu saugen.",
"ParasectPokedexEntry": "Wenn der Käfer nichts mehr zu geben hat, streuen die Pilze auf seinem Rücken Sporen auf dessen Eier.",
"VenonatPokedexEntry": "Die kleinen Insekten, die es frisst, erscheinen nur nachts, daher schläft es tagsüber in Baumlöchern.",
"VenomothPokedexEntry": "Die Schuppen, die es verstreut, lähmen jeden, der sie berührt, sodass er nicht mehr stehen kann.",
"DiglettPlainPokedexEntry": "Es gräbt unter der Erde und knabbert an Wurzeln, wobei es den Kopf nur zeigt, wenn die Sonne nicht scheint.",
"DugtrioPlainPokedexEntry": "Seine drei Köpfe wackeln einzeln auf und ab, um den Boden zu lockern und das Graben zu erleichtern.",
"MeowthPlainPokedexEntry": "Es liebt glitzernde Dinge. Sieht es etwas Schimmerndes, leuchtet auch die Münze auf seinem Kopf.",
"PersianPlainPokedexEntry": "Hinter seinem geschmeidigen, eleganten Äußeren verbirgt sich eine barbarische Seite. Es zerreißt Beute aus Laune.",
"PsyduckPokedexEntry": "Es kann seine Psycho-Kräfte nur einsetzen, wenn schlafende Gehirnzellen zufällig erwachen.",
"GolduckPokedexEntry": "Es schwimmt anmutig in den ruhigen, langsam fließenden Flüssen und Seen, die es so gern mag.",
"MankeyPokedexEntry": "Es lebt in Gruppen in den Baumkronen. Verliert es seine Gruppe aus den Augen, wird es vor Wut wütend.",
"PrimeapePokedexEntry": "Es verprügelt jeden, der es wütend macht, und verfolgt ihn bis ans Ende der Welt.",
"GrowlithePokedexEntry": "Es kontrolliert ein großes Revier. Spürt es einen fremden Geruch, brüllt es laut und vertreibt Eindringlinge.",
"ArcaninePokedexEntry": "Eine alte Bilderrolle zeigt, dass Menschen von seiner Bewegung angezogen wurden, wenn es über Prärien rannte.",
"PoliwagPokedexEntry": "Die Spirale auf seinem Bauch zeigt seine Eingeweide durch die Haut. Nach dem Essen wirkt sie klarer.",
"PoliwhirlPokedexEntry": "Obwohl es gut laufen kann, lebt es lieber unter Wasser, wo es weniger Gefahr gibt.",
"PoliwrathPokedexEntry": "Mit seinen kräftigen Armen und Beinen kann es kurz über die Wasseroberfläche laufen.",
"AbraPokedexEntry": "Es hypnotisiert sich selbst, um bei Gefahr wegzuteleportieren, selbst wenn es schläft.",
"KadabraPokedexEntry": "Schließt es die Augen, strömen doppelt so viele Alphateilchen aus der Körperoberfläche.",
"AlakazamPokedexEntry": "Es hat einen IQ von 5000. Es berechnet vieles, um im Kampf stets im Vorteil zu sein.",
"MachopPokedexEntry": "Es trainiert, indem es Felsen in den Bergen hebt. Es kann sogar einen Georok mühelos hochheben.",
"MachokePokedexEntry": "Dieses zähe #mon bleibt stets in Form. Seine Muskeln werden nach jedem Kampf dicker.",
"MachampPokedexEntry": "Mit vier Armen, die schneller reagieren als es denken kann, führt es viele Schläge gleichzeitig aus.",
"BellsproutPokedexEntry": "Bemerkt es etwas Bewegtes, schleudert es sofort seine Ranke auf das Objekt.",
"WeepinbellPokedexEntry": "Hat es Hunger, schwingt es seine messerscharfen Blätter und zerteilt alles in der Nähe als Nahrung.",
"VictreebelPokedexEntry": "Wird etwas in den Körper dieses #mon aufgenommen, schmilzt selbst das härteste Objekt dahin.",
"TentacoolPokedexEntry": "Auf den Wellen treibend nutzt es seine giftigen Tentakel, um alles zu stechen, was es berührt.",
"TentacruelPokedexEntry": "Wenn seine 80 Tentakel Wasser aufnehmen, dehnt es sich wie ein Netz aus, um Beute zu fangen.",
"GeodudePlainPokedexEntry": "Stolz auf ihren robusten Körper prallen sie gegeneinander, um zu prüfen, wessen härter ist.",
"GravelerPlainPokedexEntry": "Es rollt über Bergpfade. Wird es zu schnell, bremst es, indem es in große Felsen kracht.",
"GolemPlainPokedexEntry": "Sein felsartiger Körper ist so zäh, dass selbst Dynamit ihn nicht verletzen kann.",
"PonytaPlainPokedexEntry": "Training durch tägliches Überspringen wachsenden Grases machte es zu einem Weltklasse-Springer.",
"RapidashPlainPokedexEntry": "Es galoppiert am liebsten. Je schneller es rennt, desto länger werden die Flammen seiner Mähne.",
"SlowpokePlainPokedexEntry": "Es ist stets geistesabwesend und reagiert nicht, selbst wenn man in seinen leckeren Schweif beißt.",
"SlowbroPlainPokedexEntry": "Ein angehefteter Muschas lässt nicht los, weil der köstliche Geschmack aus seinem Schweif austritt.",
"MagnemitePokedexEntry": "Die Elektrizität der Einheiten an beiden Seiten seines Körpers machen es zu einem starken Magneten.",
"MagnetonPokedexEntry": "Wenn viele Magneton zusammenkommen, stört der magnetische Sturm die Radiowellen.",
"FarfetchDPlainPokedexEntry": "Um ihr Aussterben zu verhindern, bemühen sich mehr Menschen, diese #mon zu züchten.",
"DoduoPokedexEntry": "Indem es seine beiden Köpfe abwechselnd hebt und senkt, hält es beim Laufen das Gleichgewicht.",
"DodrioPokedexEntry": "Wer auch nur einen der drei Köpfe eine Sekunde aus den Augen lässt, wird heftig gepickt.",
"SeelPokedexEntry": "Das hellblaue Fell schützt es vor Kälte. Es liebt Ozeane voller Eisberge.",
"DewgongPokedexEntry": "Tagsüber schläft es in flachen Meeresgewässern und sucht nachts bei Kälte nach Nahrung.",
"GrimerPlainPokedexEntry": "Wenn sich zwei dieser #mon-Körper verbinden, entstehen neue Gifte.",
"MukPlainPokedexEntry": "Beim Fortbewegen sickert starkes Gift aus, das den Boden drei Jahre lang unfruchtbar macht.",
"ShellderPokedexEntry": "Beim Zukneifen eines Gegners werden verwundbare Stellen sichtbar, daher nutzt es das nur im Notfall.",
"CloysterPokedexEntry": "Selbst eine Rakete kann die Stacheln nicht brechen, mit denen es Gegner angreift. Sie sind härter als sein Panzer.",
"GastlyPokedexEntry": "Es hüllt Gegner in seinen gasartigen Körper und schwächt Beute langsam durch Hautvergiftung.",
"HaunterPokedexEntry": "Es lauert im Dunkeln und plant, das nächste Lebewesen zu töten, das sich nähert.",
"GengarPokedexEntry": "Nachts versteckt es sich in Menschenschatten und saugt deren Wärme ab. Das verursacht Schaudern.",
"OnixPokedexEntry": "Beim Graben absorbiert es viele harte Objekte, wodurch sein Körper so fest wird.",
"DrowzeePokedexEntry": "Zuckt es mit der Nase, kann es erkennen, wo jemand schläft und wovon er träumt.",
"HypnoPokedexEntry": "Je länger es sein Pendel schwingt, desto länger wirkt seine Hypnose.",
"KrabbyPokedexEntry": "Findet es keine Nahrung, nimmt es Nährstoffe auf, indem es eine Handvoll Sand verschluckt.",
"KinglerPokedexEntry": "Seine riesige Schere ist sehr stark, doch außerhalb des Kampfes ist sie nur hinderlich.",
"VoltorbPokedexEntry": "Bei der Erforschung dieses #mon stellte man fest, dass seine Bestandteile in der Natur nicht vorkommen.",
"ElectrodePokedexEntry": "Je mehr Energie es speichert, desto schneller wird es. Das erhöht aber auch die Explosionsgefahr.",
"ExeggcutePokedexEntry": "Wird auch nur eines von sechs getrennt, zieht die Energiebindung sie sofort wieder zusammen.",
"ExeggutorPlainPokedexEntry": "Lebt es in guter Umgebung, wachsen viele Köpfe. Ein abfallender Kopf wird zu einem Owei.",
"CubonePokedexEntry": "Es verlor seine Mutter nach der Geburt. Es trägt ihren Schädel und zeigt nie sein wahres Gesicht.",
"MarowakPlainPokedexEntry": "Irgendwo auf der Welt gibt es einen Friedhof nur für Knogga. Dort holt es sich seine Knochen.",
"HitmonleePokedexEntry": "Es wird auch Meister des Tritts genannt. Mit elastischen Beinen führt es jeden bekannten Tritt aus.",
"HitmonchanPokedexEntry": "Um alle Schläge zu verstärken, wirbelt es die Arme kurz vor dem Treffer.",
"LickitungPokedexEntry": "Seine Zunge hat feine Nerven bis zur Spitze und kann geschickt bewegt werden.",
"KoffingPokedexEntry": "Kommt man seinem Giftgas nahe genug, kann man das wirbelnde Gas in seinem Inneren sehen.",
"WeezingPlainPokedexEntry": "Atmet es giftige Gase aus Müll ein, dehnt sich sein Körper und es riecht noch schlimmer innen.",
"RhyhornPokedexEntry": "Es kann sich nur an eine Sache gleichzeitig erinnern. Hat es Anlauf genommen, vergisst es warum.",
"RhydonPokedexEntry": "Dreht es leicht sein bohrerartiges Horn, zerschmettert es selbst einen rohen Diamanten.",
"ChanseyPokedexEntry": "Menschen versuchen es wegen seiner nahrhaften Eier zu fangen, doch es ist selten zu finden.",
"TangelaPokedexEntry": "Im Kampf bewegt es ständig die Ranken auf seinem Körper, um den Gegner zu ärgern.",
"KangaskhanPokedexEntry": "Um das Junge in seinem Beutel nicht zu zerdrücken, schläft es stets im Stehen.",
"HorseaPokedexEntry": "An sicheren Orten sieht man sie spielerisch ihre Schweife miteinander verflechten.",
"SeadraPokedexEntry": "Das Männchen zieht die Jungen auf. Wird es bedrängt, wehrt es sich mit giftigen Stacheln.",
"GoldeenPokedexEntry": "In der Laichzeit schwimmen sie anmutig im Wasser und suchen ihren idealen Partner.",
"SeakingPokedexEntry": "Im Herbst patrouillieren die Männchen um ihr Nest, um ihren Nachwuchs zu schützen.",
"StaryuPokedexEntry": "Wenn die Sterne nachts funkeln, steigt es vom Meeresboden empor und sein Kern leuchtet auf.",
"StarmiePokedexEntry": "Man sagt, es nutze den siebenfarbigen Kern seines Körpers, um elektrische Wellen ins All zu senden.",
"MrMimePlainPokedexEntry": "Mit der geheimnisvollen Kraft in seinen Fingern verfestigt es Luft zu einer unsichtbaren Wand.",
"ScytherPokedexEntry": "Es ist sehr stolz auf seine Schnelligkeit. Es bewegt sich so schnell, dass Gegner nicht wissen, was sie traf.",
"JynxPokedexEntry": "Es hat verschiedene Rufmuster, von denen jedes eine eigene Bedeutung zu haben scheint.",
"ElectabuzzPokedexEntry": "Berühren sich zwei Elektek, steuern sie elektrische Ströme, um Gefühle auszudrücken.",
"MagmarPokedexEntry": "In heißen Gebieten ist es aktiver. Es heilt Wunden, indem es sie in Lava taucht.",
"PinsirPokedexEntry": "Sinkt nachts die Temperatur, schläft es auf Baumkronen oder zwischen Wurzeln, gut versteckt.",
"TaurosPlainPokedexEntry": "Diese wilden #mon kämpfen mit anderen Herdmitgliedern, um ihre Stärke zu beweisen.",
"MagikarpPokedexEntry": "Dieses schwache #mon wird bei starken Strömungen in Flüssen einfach mitgerissen.",
"GyaradosPlainPokedexEntry": "Es erscheint bei weltweiten Konflikten und verbrennt jeden Ort, den es durchquert.",
"LaprasPokedexEntry": "Dieses sanfte #mon trägt Menschen gern und bietet eine sehr bequeme Art zu reisen.",
"DittoPokedexEntry": "Trifft es auf ein anderes Ditto, bewegt es sich schneller, um den Gegner exakt zu kopieren.",
"EeveePokedexEntry": "Seine vielen Entwicklungsformen ermöglichen eine perfekte Anpassung an jede Umgebung.",
"VaporeonPokedexEntry": "Mit den Flossen an der Schweifspitze schwimmt es und verschmilzt perfekt mit dem Wasser.",
"JolteonPokedexEntry": "Negative Ionen in seinem Fell erzeugen ein ständiges Knistern.",
"FlareonPokedexEntry": "Hat es genug Hitze gespeichert, kann seine Körpertemperatur bis 1700 Grad steigen.",
"PorygonPokedexEntry": "Ein künstliches #mon aus Forschung. Es kann nur das ausführen, was in seinem Programm steht.",
"OmanytePokedexEntry": "In der Urzeit schwamm es auf dem Meeresboden und fraß Plankton. Fossilien werden gefunden.",
"OmastarPokedexEntry": "Sein schwerer Panzer ließ es nur nahe Nahrung erreichen. Das könnte sein Aussterben erklären.",
"KabutoPokedexEntry": "Vor 300 Millionen Jahren versteckte es sich auf dem Meeresboden. Augen auf dem Rücken leuchten.",
"KabutopsPokedexEntry": "Es schwamm schnell, indem es seine scharfen Sicheln kompakt anlegte.",
"AerodactylPokedexEntry": "In der Urzeit flog dieses #mon frei und furchtlos durch die Lüfte.",
"SnorlaxPokedexEntry": "Der Magen dieses #mon ist so stark, dass selbst schimmelige oder verrottete Nahrung ihm nichts ausmacht.",
"ArticunoPlainPokedexEntry": "Legendäres Vogel-#mon. Beim Flug kühlt es die Luft und lässt Schnee fallen.",
"ZapdosPlainPokedexEntry": "Legendäres Vogel-#mon. Man sagt, Blitze durch Flügelschläge lösen Sommergewitter aus.",
"MoltresPlainPokedexEntry": "Legendäres Vogel-#mon. Es soll mit dem Frühling aus dem Süden wandern.",
"DratiniPokedexEntry": "Es häutet sich oft beim Wachsen. Dabei schützt es ein reißender Wasserfall.",
"DragonairPokedexEntry": "Man nennt es das göttliche #mon. Leuchtet sein Körper auf, ändert sich das Wetter.",
"DragonitePokedexEntry": "Man sagt, irgendwo im Ozean liegt eine Insel, auf der nur diese leben.",
"MewtwoPlainPokedexEntry": "Man sagt, es ruhe still in einer unentdeckten Höhle. Es wurde nur zum Kämpfen erschaffen.",
"MewPokedexEntry": "Da es jeden Angriff lernen kann, vermuten manche, es sei der Urahn aller #mon.",
"ChikoritaPokedexEntry": "Es liebt es, in der Sonne zu baden. Mit dem Blatt auf dem Kopf sucht es warme Plätze.",
"BayleefPokedexEntry": "Der Duft der Blätter an seinem Hals macht jeden, der ihn riecht, energiegeladen.",
"MeganiumPokedexEntry": "Wer neben ihm steht, fühlt sich erfrischt, als läge er in einem sonnigen Wald.",
"CyndaquilPokedexEntry": "Das Feuer auf seinem Rücken brennt am heißesten, wenn es wütend ist. Die Flammen schrecken Gegner.",
"QuilavaPokedexEntry": "Vor dem Kampf wendet es dem Gegner den Rücken zu, um die Heftigkeit seiner Flammen zu zeigen.",
"TyphlosionPlainPokedexEntry": "Wenn die Körperhitze die Luft flimmern lässt, ist es kampfbereit.",
"TotodilePokedexEntry": "Dieses wilde Tier schnappt nach allem Bewegten. Den Rücken kehren ist nicht ratsam.",
"CroconawPokedexEntry": "Die Fangspitzen sind schräg nach hinten gerichtet. Einmal zugebissen, gibt es keine Flucht.",
"FeraligatrPokedexEntry": "Trotz seines massiven Körpers bewegt es sich dank kräftiger Hinterbeine schnell am Boden.",
"SentretPokedexEntry": "Als Wache warnt es andere vor Gefahr durch Kreischen und Schlagen mit dem Schweif.",
"FurretPokedexEntry": "Es lebt in schmalen Röhren, die zu seinem schlanken Körper passen. Tiefe Nester sind labyrinthartig.",
"HoothootPokedexEntry": "Es beginnt täglich zur gleichen Zeit zu rufen. Manche Trainer nutzen es als Uhr.",
"NoctowlPokedexEntry": "Seine weichen Federn machen keinen Laut im Flug. Es schleicht sich unbemerkt an Beute heran.",
"LedybaPokedexEntry": "Es ist scheu und hält sich in Gruppen. Die Flüssigkeit an seinen Füßen verrät seinen Standort.",
"LedianPokedexEntry": "Wird es tagsüber warm, rollt es sich in ein großes Blatt und schläft tief.",
"SpinarakPokedexEntry": "Ist Beute in seinem Spinnennetz gefangen, wartet es regungslos, bis es dunkel wird.",
"AriadosPokedexEntry": "Statt ein Nest zu bauen, streift es nach Einbruch der Dunkelheit auf Nahrungssuche umher.",
"CrobatPokedexEntry": "Auf der Jagd nach schnellerem, leiserem Flug wuchsen ihm neue Flügel an den Hinterbeinen.",
"ChinchouPokedexEntry": "Seine aus einer Flosse entstandenen Antennen leiten positive und negative Ladungen.",
"LanturnPokedexEntry": "Dieses #mon nutzt den leuchtenden Teil seines Körpers, einst eine Rückenflosse, um Beute anzulocken.",
"PichuPokedexEntry": "Es kann Elektrizität noch nicht gut speichern. Jeder Schock lässt es Energie entweichen.",
"CleffaPokedexEntry": "Findet man eine Meteoritenkraterstelle, ist dieses #mon sicher in der Nähe.",
"IgglybuffPokedexEntry": "Statt mit kurzen Beinen zu laufen, hüpft es auf seinem weichen, zarten Körper umher.",
"TogepiPokedexEntry": "Es gilt als Glückssymbol. Man sagt, seine Schale sei voller Freude.",
"TogeticPokedexEntry": "Obwohl es die Flügel wenig schlägt, kann es fliegen und seinem Trainer folgen.",
"NatuPokedexEntry": "Es klettert ausgezeichnet an Baumstämmen und frisst gern frische Triebe.",
"XatuPokedexEntry": "Beginnt es bei Sonnenaufgang zu meditieren, vergeht ein ganzer Tag, bevor es sich rührt.",
"MareepPokedexEntry": "Es speichert viel Luft in seinem weichen Fell und bleibt so im Sommer kühl und im Winter warm.",
"FlaaffyPokedexEntry": "Dank gummiartiger, stromresistenter Haut kann es viel Elektrizität im Fell speichern.",
"AmpharosPokedexEntry": "Wird es dunkel, ist das Licht seines hellen Schweifs weit über dem Meer zu sehen.",
"BellossomPokedexEntry": "Tanzen sie zusammen, reiben sich ihre Blütenblätter und erzeugen schöne, beruhigende Klänge.",
"MarillPokedexEntry": "Sein Fell weist Wasser von selbst ab. Es bleibt trocken, auch wenn es im Wasser spielt.",
"AzumarillPokedexEntry": "Das blasenartige Muster auf seinem Bauch hilft ihm, sich im Wasser zu tarnen.",
"SudowoodoPokedexEntry": "Zittert ein Ast ohne Wind, ist es ein Mogelbaum, kein Baum. Es versteckt sich vor Regen.",
"PolitoedPokedexEntry": "Dehnt es die Kehle zum Quaken, versammeln sich sofort Quapsel und Quaputzi.",
"HoppipPokedexEntry": "Schon die leiseste Brise kann es forttragen. Es schwebt bis in die nächste Stadt.",
"SkiploomPokedexEntry": "Bei Regen schließt es seine Blüte und versteckt sich schattig unter einem Baum.",
"JumpluffPokedexEntry": "Selbst im stärksten Wind steuert es seine Flaumhaare und reist überall hin.",
"AipomPokedexEntry": "Es hängt mit dem Schweif an Ästen und schwingt sich von Zweig zu Zweig.",
"SunkernPokedexEntry": "Es ist sehr schwach. Seine einzige Verteidigung ist verzweifeltes Schütteln der Blätter.",
"SunfloraPokedexEntry": "Mit der Hitzezeit werden die Blütenblätter an seinem Gesicht lebhafter und farbenfroher.",
"YanmaPokedexEntry": "Es sieht in alle Richtungen, ohne die großen Augen zu bewegen, und erkennt Gegner und Nahrung sofort.",
"WooperPlainPokedexEntry": "Eine Schleimhaut bedeckt seinen Körper. Berührt man sie barhändig, schmerzt es heftig.",
"QuagsirePokedexEntry": "Sein Körper ist stets schleimig. Beim Schwimmen stößt es oft den Kopf an, scheint es aber nicht zu stören.",
"EspeonPokedexEntry": "Die Spitze seines gegabelten Schweifs zuckt, wenn es die nächste Bewegung des Gegners vorhersagt.",
"UmbreonPokedexEntry": "Bei Vollmond oder Aufregung leuchten die Ringmuster auf seinem Körper gelb.",
"MurkrowPokedexEntry": "Es versteckt glänzende Fundstücke an geheimen Orten. Kramurx und Mauzi plündern gegenseitig.",
"SlowkingPlainPokedexEntry": "Bei jedem Gähnen spritzt Muschas mehr Gift, das es intelligenter macht.",
"MisdreavusPokedexEntry": "Es liebt es, Menschen zu beobachten, die es erschreckt, durch laute Schreie oder plötzliches Erscheinen.",
"UnownPokedexEntry": "Da es viele Unown-Formen gibt, vermutet man, dass sie verschiedene Kräfte besitzen.",
"WobbuffetPokedexEntry": "Um seinen schwarzen Schweif zu verbergen, lebt es in dunklen Höhlen und bewegt sich nur nachts.",
"GirafarigPokedexEntry": "In Gefahr nutzt sein Schweif geheimnisvolle Kräfte, um den Feind zu vertreiben.",
"PinecoPokedexEntry": "Es spuckt eine Flüssigkeit aus, mit der es Baumrinde an seinen Körper klebt. Sie härtet an der Luft.",
"ForretressPokedexEntry": "Es hängt meist an dicken Baumstämmen. Bei Gefahr schießt es Panzerteile ab.",
"DunsparcePokedexEntry": "Es versteckt sich tief in Höhlen ohne Licht und bleibt dort fast regungslos.",
"GligarPokedexEntry": "Es baut sein Nest an steilen Klippen. Nach dem Gleiten hüpft es zurück zum Nest.",
"SteelixPokedexEntry": "Die vielen kleinen Metallpartikel auf seinem Körper reflektieren helles Licht stark.",
"SnubbullPokedexEntry": "In Wahrheit ist es ein Feigling. Es knurrt eifrig, um seine Angst zu verbergen.",
"GranbullPokedexEntry": "Öffnet es weit das Maul und zeigt große Fangzähne, flieht fast jedes #mon.",
"QwilfishPokedexEntry": "Steht es einem größeren Gegner gegenüber, schluckt es Wasser, um dessen Größe zu erreichen.",
"ScizorPokedexEntry": "Die stählernen Scheren dieses #mon zermalmen jedes harte Objekt, das sie packen.",
"ShucklePokedexEntry": "Die Flüssigkeit an seinen Zehen gräbt Löcher in Felsen und lässt sich mit Beeren zu Getränken mischen.",
"HeracrossPokedexEntry": "Mit Herkules-Kraft kann es mühelos etwas werfen, das das Hundertfache seines Gewichts hat.",
"SneaselPokedexEntry": "Dieses listige #mon lauert im Dunkeln und greift Beute an.",
"TeddiursaPokedexEntry": "Es leckt ständig Honig. Seine Pfote schmeckt süß vom vielen Honig.",
"UrsaringPokedexEntry": "Trotz großem Körper klettert es geschickt auf Bäume, frisst und schläft in den Kronen.",
"SlugmaPokedexEntry": "Sie sammeln sich in besonders heißen Gebieten. Kühlt es ab, wird die Haut hart.",
"MagcargoPokedexEntry": "Sein Körper ist heiß wie Lava und dampft ständig. Flammen schießen gelegentlich aus dem Panzer.",
"SwinubPokedexEntry": "Mit der Nasenspitze wühlt es nach Nahrung. Die Nase ist so hart, dass selbst gefrorener Boden kein Problem ist.",
"PiloswinePokedexEntry": "Obwohl die Beine kurz sind, verhindern robuste Hufe ein Ausrutschen, selbst auf Eis.",
"CorsolaPlainPokedexEntry": "Die Punkte auf seinem Kopf nehmen Nährstoffe aus sauberem Wasser auf. Verschmutztes Wasser tötet es.",
"RemoraidPokedexEntry": "Zur Flucht schießt es Wasser aus dem Maul und nutzt den Rückstoß zum Schwimmen.",
"OctilleryPokedexEntry": "Sein Instinkt ist, sich in Löcher zu verkriechen. Es stiehlt oft fremde Nester zum Schlafen.",
"DelibirdPokedexEntry": "Es trägt überall seine Nahrung mit. Wird es angegriffen, wirft es das Futter auf den Gegner.",
"MantinePokedexEntry": "Es schwimmt frei und frisst alles, was in sein Maul schwimmt. Sein ganzer Körper ist rau.",
"SkarmoryPokedexEntry": "Seine abgeworfenen Federn sind sehr scharf. Man sagt, man habe sie einst als Schwerter genutzt.",
"HoundourPokedexEntry": "Gegen Morgengrauen hallt sein unheimliches Heulen durch das Gebiet und markiert sein Revier.",
"HoundoomPokedexEntry": "Die stinkende Flamme aus seinem Maul entsteht, wenn Gift in seinem Körper verbrennt.",
"KingdraPokedexEntry": "Es speichert Energie, indem es in Tiefen schläft, in denen kein anderes Leben überlebt.",
"PhanpyPokedexEntry": "In der stillen Morgendämmerung kommt es ans Ufer und duscht geschickt mit seinem Rüssel.",
"DonphanPokedexEntry": "Da die Haut dieses #mon so zäh ist, hinterlässt ein normaler Angriff nicht mal eine Schramme.",
"Porygon2PokedexEntry": "Dieses künstliche #mon entwickelte sich durch neue Technologie. Es zeigt unprogrammierte Reaktionen.",
"StantlerPokedexEntry": "Die Kugeln abgeworfener Geweihe lassen sich zu Pulver mahlen, das beim Einschlafen hilft.",
"SmearglePokedexEntry": "Die Farbe der geheimnisvollen Flüssigkeit aus seinem Schweif ist für jedes Farbebe bestimmt.",
"TyroguePokedexEntry": "Um seine Kampfkünste zu üben, fordert es jeden heraus. Es hat einen starken Ehrgeiz.",
"HitmontopPokedexEntry": "Nach einem Handstand, der den Gegner verwirrt, zeigt es seine kunstvollen Tritte.",
"SmoochumPokedexEntry": "Die Empfindlichkeit seiner Lippen entwickelt sich am schnellsten. Damit erkundet es Unbekanntes.",
"ElekidPokedexEntry": "Es liebt heftigen Donner. Zwischen seinen Hörnern flackert es bläulich-weiß beim Aufladen.",
"MagbyPokedexEntry": "Es spuckt von Natur aus 1100-Grad-Flammen. Viele deuten auf einen Vulkanausbruch hin.",
"MiltankPokedexEntry": "Um eine Miltank zu melken, braucht man ein Gefühl für rhythmisches Ziehen an ihren Zitzen.",
"BlisseyPokedexEntry": "Ein Biss in eines ihrer leckeren Eier lässt alle in der Nähe vor Freude lächeln.",
"RaikouPokedexEntry": "Dieses wilde #mon speichert Energie im Körper und fegt über das Land, Elektrizität ausstoßend.",
"EnteiPokedexEntry": "Dieses kräftige #mon durchquert die Erde und speit Flammen, heißer als Magma.",
"SuicunePokedexEntry": "Dieses göttliche #mon zieht um die Welt und sucht stets ein reines Reservoir.",
"LarvitarPokedexEntry": "Tief unter der Erde geboren wird es nach genug Erde eine Puppe.",
"PupitarPokedexEntry": "Selbst als Puppe ruht es nicht. Unter dem festen Panzer hat es schon Arme und Beine.",
"TyranitarPokedexEntry": "Mit einer Hand kann es den Boden erbeben lassen und Berge zum Einsturz bringen.",
"LugiaPokedexEntry": "Es kann tobende Stürme beruhigen. Man sagt, Lugia erscheint, wenn Stürme beginnen.",
"HoOhPokedexEntry": "Es zeigt sich reinen Herzens vor einem Trainer und lässt seine Regenbogenflügel leuchten.",
"CelebiPokedexEntry": "Als Hüter des Waldes verehrt, erscheint Celebi, wo schöne Wälder existieren.",
"AzurillPokedexEntry": "Sein Schweif enthält Nährstoffe fürs Wachstum. Es spielt, indem es auf dem Schweif hüpft.",
"WynautPokedexEntry": "Es bewegt sich meist im Rudel. Einzelne drücken sich zusammen, um ihren Mut zu stärken.",
"AmbipomPokedexEntry": "Geteilte Schweife sind so geschickt, dass Ambidiffel seine Hände kaum noch nutzt.",
"MismagiusPokedexEntry": "Seine Rufe klingen wie Beschwörungen zur Qual des Gegners. Es erscheint unerwartet.",
"HonchkrowPokedexEntry": "Es ist von Natur aus gnadenlos und verzeiht Fehler seiner Kramurx-Anhänger nie.",
"BonslyPokedexEntry": "Es bevorzugt trockene Luft. Beim Feuchtigkeitsausgleich tropft wassertropfenartige Flüssigkeit.",
"MimeJrPokedexEntry": "Es ahmt Mimik und Gesten nach, um die Gefühle anderer zu verstehen.",
"HappinyPokedexEntry": "Es trägt einen runden, eiförmigen Stein im Bauchbeutel und schenkt ihn Freunden.",
"MunchlaxPokedexEntry": "In seiner Gier zu fressen vergisst es das Futter, das es im Fell versteckt hat.",
"MantykePokedexEntry": "Man organisiert Touren, um dieses #mon mit Remoraid über die Wellen gleiten zu sehen.",
"WeavilePokedexEntry": "Es lebt in Schneeregionen und ritzt mit Krallen Muster in Bäume als Signal.",
"MagnezonePokedexEntry": "Es entwickelte sich durch ein spezielles Magnetfeld. Drei Einheiten erzeugen Magnetismus.",
"LickilickyPokedexEntry": "Die lange Zunge ist stets mit Speichel benetzt. Er enthält ein betäubendes Lösungsmittel.",
"RhyperiorPokedexEntry": "Aus Löchern in seinen Handflächen schießt es Georok. Sein Panzer hält Vulkanausbrüche stand.",
"TangrowthPokedexEntry": "Es fängt Beute mit aus Ranken gewachsenen Armen. Verliert es welche, stört das es nicht.",
"ElectivirePokedexEntry": "Es drückt die Schweifspitzen an den Gegner und entlädt über 20000 Volt.",
"MagmortarPokedexEntry": "Viele Fabriken nutzen noch die Flammen von Magbrust zur Metallverarbeitung.",
"TogekissPokedexEntry": "Es segnet Menschen, die einander respektieren und unnötigen Streit meiden.",
"YanmegaPokedexEntry": "Seine Kieferkraft ist enorm. Im Flug beißt es Gegner im Vorbeisausen auseinander.",
"LeafeonPokedexEntry": "Wie eine Pflanze nutzt es Photosynthese und ist stets von klarer Luft umgeben.",
"GlaceonPokedexEntry": "Es erzeugt kleine Eiskristalle, indem es die Temperatur der Umgebungsluft senkt.",
"GliscorPokedexEntry": "Sein Flug ist lautlos. Mit dem langen Schweif trägt es Beute fort, dann greifen die Fangzähne.",
"MamoswinePokedexEntry": "Seine Stoßzähne bestehen aus Eis. Nach der Eiszeit wurde die Population kleiner.",
"PorygonZPokedexEntry": "Sein Programm wurde für fremde Dimensionen geändert. Es funktionierte nicht wie geplant.",
"SylveonPokedexEntry": "Es wickelt bandartige Fühler um den Arm seines geliebten Trainers und geht mit ihm.",
"PerrserkerPokedexEntry": "Nach vielen Kämpfen entwickelte es gefährliche Krallen, die wie Dolche wirken.",
"CursolaPokedexEntry": "Vorsicht vor dem ectoplasmischen Körper um seine Seele. Berührung lässt einen erstarren.",
"SirfetchDPokedexEntry": "Nach dem Abwehren mit dem harten Blattschild schlägt es mit dem scharfen Lauch zurück.",
"MrRimePokedexEntry": "Es ist sehr begabt im Stepptanz und schwingt seinen Eisstock im Takt eleganter Bewegungen.",
"WyrdeerPokedexEntry": "Das Bartfell hält Wärme gut und ist ein wertvoller Stoff für Winterkleidung.",
"KleavorPokedexEntry": "Es fällt mit groben Äxten hohe Bäume und schützt sich mit hartem Stein.",
"UrsalunaPokedexEntry": "Dieses #mon hat einen kräftigen Körper und kann Torf nach Belieben formen.",
"SneaslerPokedexEntry": "Es hat virulentes Gift und starke Körperkraft. Es lebt lieber allein als im Rudel.",
"OverqwilPokedexEntry": "Stacheln und wildes Temperament brachten ihm den Namen Meeresungeheuer. Es schlürft Gift.",
"DudunsparcePokedexEntry": "Mit dem harten Schweif bohrt es Nester in tiefes Gestein. Sie können über zehn Kilometer reichen.",
"FarigirafPokedexEntry": "Da Hirnwellen von Kopf und Schweif synchron sind, ist seine Psycho-Kraft zehnmal stärker.",
"ClodsirePokedexEntry": "Wird es angegriffen, stößt es dicke Stacheln aus dem Körper. Ein riskanter Schachzug.",
"AnnihilapePokedexEntry": "Als seine Wut einen kritischen Punkt überschritt, erlangte es Kraft jenseits seines Körpers.",
"GyaradosRedPokedexEntry": "Durch die rasche Zwangsentwicklung behielt dieses Garados die roten Schuppen eines Karpador.",
"MewtwoArmoredPokedexEntry": "Mit verstärkter Verteidigung und verstärkten Psycho-Angriffen durch die Rüstung ist Mewtu unaufhaltsam.",
"RattataAlolanPokedexEntry": "Es interessiert sich nur für Frisches. Nimmst du es einkaufen, hilft es bei der Auswahl.",
"RaticateAlolanPokedexEntry": "Es lässt Rattfratz-Untergebene Nahrung sammeln und frisst nur das Beste.",
"RaichuAlolanPokedexEntry": "Reibt man seine Wangen, verströmt es einen süßen Duft. Man bekommt aber auch einen leichten Schock.",
"SandshrewAlolanPokedexEntry": "Es lebt auf Schneebergen. Sein Stahlpanzer ist so hart, dass es sich nicht einrollen kann.",
"SandslashAlolanPokedexEntry": "Viele klettern auf Schneeberge, um die Eiszapfen dieses #mon im Morgenlicht zu sehen.",
"VulpixAlolanPokedexEntry": "Betrachtet man seine lockigen Haare im Mikroskop, sieht man kleine Eiskristalle entstehen.",
"NinetalesAlolanPokedexEntry": "Es führt Menschen den Berg hinab, damit sie schnell gehen und das Gebiet verlassen.",
"DiglettAlolanPokedexEntry": "Das metallreiche Gestein seiner Heimat ließ Stahlbarthaare auf seinem Kopf wachsen.",
"DugtrioAlolanPokedexEntry": "Seine metallischen Barthaare sind schwer, daher ist es langsam, kann aber durch Fels graben.",
"MeowthAlolanPokedexEntry": "Hochintelligent und stolz, ist es berühmt schwer zu zähmen. Das macht es auch beliebt.",
"GrimerAlolanPokedexEntry": "Ein zur Müllbeseitigung eingesetztes Sleima entwickelte sich zu dieser Form.",
"MukAlolanPokedexEntry": "Sleimoks Färbung wird lebhafter, je mehr es von seinem Lieblingsgericht Müll frisst.",
"ExeggutorAlolanPokedexEntry": "Es schwingt den langen Hals wie eine Peitsche gegen Gegner. Dadurch wird auch es selbst schwindelig.",
"MarowakAlolanPokedexEntry": "Es entzündet den Knochen in der Hand und tanzt nachts, um gefallene Gefährten zu betrauern.",
"MeowthGalarianPokedexEntry": "Diese mutigen #mon haben Münzen auf der Stirn. Härtere Münzen bringen mehr Respekt.",
"PersianAlolanPokedexEntry": "Es hat das edelste Fell. Das Wellen im Kampf hat eine eigene Schönheit.",
"GeodudeAlolanPokedexEntry": "Sein Körper ist magnetischer Stein. Eisensand haftet an den stärksten magnetischen Stellen.",
"GravelerAlolanPokedexEntry": "Sein ganzer Körper ist elektrisch geladen durch die Steine, die es frisst. Es ist sehr jähzornig.",
"GolemAlolanPokedexEntry": "Es schießt elektrisch geladene Felsen. Schrammt man nur daran, wird man betäubt.",
"PonytaGalarianPokedexEntry": "Es blickt dir in die Augen und liest dein Herz. Findet es Böses, zieht es sich zurück.",
"RapidashGalarianPokedexEntry": "Ein Psycho-Angriff aus seinem Horn kann selbst dickes Blech durchschlagen.",
"SlowpokeGalarianPokedexEntry": "Normalerweise träumerisch, wird sein Blick manchmal plötzlich scharf. Vielleicht liegt es am Futter.",
"SlowbroGalarianPokedexEntry": "Ein Muschas-Biss löste eine chemische Reaktion aus und machte Lahmus zu einem Gift-#mon.",
"FarfetchDGalarianPokedexEntry": "Diese besonderen Porenta sind tapfere Krieger und kämpfen mit dicken, festen Lauchstangen.",
"WeezingGalarianPokedexEntry": "Es nimmt verschmutzte Luftpartikel auf. Statt Kot auszuscheiden, stößt es saubere Luft aus.",
"MrMimeGalarianPokedexEntry": "Es kann Kälte von den Fußsohlen abgeben und tanzt den ganzen Tag auf gefrorenem Boden.",
"ArticunoGalarianPokedexEntry": "Als Arktos bekannt, feuert dieses #mon Strahlen ab, die Gegner wie erstarrt lähmen.",
"ZapdosGalarianPokedexEntry": "Wenn sich seine Federn reiben, entsteht ein Knistern wie elektrische Entladungen.",
"MoltresGalarianPokedexEntry": "Die finstere Aura um dieses #mon, die wie Feuer lodert, gab ihm den Namen Lavados.",
"SlowkingGalarianPokedexEntry": "Gift und der Schock der Entwicklung ließen Muschas die Kontrolle über Laschoking übernehmen.",
"CorsolaGalarianPokedexEntry": "Plötzlicher Klimawandel löschte dieses #mon aus. Es saugt über Äste fremde Lebenskraft.",
"GrowlitheHisuianPokedexEntry": "Sie patrouillieren zu zweit ihr Revier. Ihr Fell enthält vulkanisches Gestein.",
"ArcanineHisuianPokedexEntry": "Trotz seiner Masse fintiert es geschickt und führt Gegner beim Tanz vorbei.",
"VoltorbHisuianPokedexEntry": "Wird es aufgeregt, entlädt es Strom aus dem Bauch und lacht dabei.",
"ElectrodeHisuianPokedexEntry": "Das Gewebe an seiner Oberfläche ähnelt stark einer Aprikoko.",
"TyphlosionHisuianPokedexEntry": "Man sagt, es reinige verlorene Seelen mit seinen Flammen und geleite sie ins Jenseits.",
"QwilfishHisuianPokedexEntry": "Fischer hassen es, weil es Gift aus Stacheln spritzt und alles besprüht.",
"SneaselHisuianPokedexEntry": "Seine robusten Krallen eignen sich fürs Klettern. Sie tropfen Gift in die Beute.",
"WooperPaldeanPokedexEntry": "Sie gehen zu dritt oder viert und helfen einander beim Gang durch gefährliche Sümpfe.",
"TaurosPaldeanPokedexEntry": "Die Kampfrasse kämpft aus nächster Nähe und trifft mit kurzen Hörnern Schwachstellen.",
"TaurosPaldeanFirePokedexEntry": "Die Hörner der Flammenrasse erreichen über 1800 Grad. Aufstoß verursacht Brandwunden.",
"TaurosPaldeanWaterPokedexEntry": "Die Aqua-Rasse schwimmt, indem es Wasser aus den Hörnern spritzt. Hoher Körperfettanteil lässt es schweben.",
"UrsalunaBloodmoonPokedexEntry": "Mit dem linken Auge sieht es im Dunkeln und schützt sich mit hartem Schlamm wie Eisen.",
}